/**
 * Centralized language layer — single source of truth for user-facing strings.
 * PRIMARY: Tunisian Derja (default, RTL). SECONDARY: French, English (LTR).
 * Persisted in localStorage; document.dir follows the language.
 * Technical identifiers, protocol names and code constants stay untranslated.
 */
import { useEffect, useState } from "react";

export type Lang = "tu" | "fr" | "en";

const STRINGS: Record<Lang, Record<string, string>> = {
  tu: {
    nav_home: "جينيو",
    nav_explore: "استكشف", nav_security: "الأمان", nav_docs: "الوثائق",
    nav_download: "تحميل", nav_install: "ركّب Genio توّا", nav_app: "التطبيق",
    install_title: "ركّب Genio توّا", try: "جرّب Genio", docs: "الوثائق",
    offline: "ما فماش اتصال بالإنترنت", error: "صار مشكل",
    retry: "عاود المحاولة", task: "المهمّة", evidence: "الدليل",
    settings: "الإعدادات", assistant: "المساعد", start: "إبدا",
    tools_activity: "نشاط الأدوات",
    // footer.* (public portal footer)
    "footer.docs": "الوثائق",
    "footer.security": "الأمان",
    "footer.api": "API",
    "footer.tag": "سيادي • HiTechLab 🇹🇳",
    // landing.* (public landing page — Tunisian-first)
    "landing.brand_tag": "جينيو",
    "landing.live": "SYSTEM LIVE",
    "landing.founder": "المؤسس",
    "landing.enter_app": "ادخل للتطبيق",
    "landing.hero_badge": "أول صاحب ذكاء اصطناعي تونسي — بالدارجة",
    "landing.hero_title_a": "أول صاحب",
    "landing.hero_title_b": "ذكاء اصطناعي",
    "landing.hero_title_c": "تونسي",
    "landing.hero_sub": "جينيو يفهمك بالدارجة، ينظّم خدمتك، يبرمج، يراقب السيرفرات، ويخلّيك تتحكم في دارك الذكية — من تليفونك ولا حاسوبك. خصوصية مضمونة، يعمل محلي ولا سحابي حسب اختيارك.",
    "landing.cta_try": "جرّب Genio توة ←",
    "landing.cta_install": "ركّب Genio توّا ↓",
    "landing.cta_how": "كيفاش يخدم؟",
    "landing.product_explore": "استكشف",
    "landing.product_download": "تحميل",
    "landing.product_install": "التثبيت",
    "landing.product_docs": "الوثائق",
    "landing.product_security": "الأمان",
    "landing.no_key_note": "لا API key في المتصفح • يعمل أوفلاين Tier A • صوت و صورة",
    "landing.how_title": "كيفاش يخدم — 3 خطوات",
    "landing.how_1t": "احكي بالدارجة",
    "landing.how_1d": "اكتب ولا احكي: «نظّملي السيرفر» ولا «شغّل الضو» — جينيو يفهم عربي، دارجة، فرنسي وانجليزي.",
    "landing.how_2t": "جينيو يخطط وينفّذ",
    "landing.how_2d": "يحلّل طلبك، يستعمل الأدوات (bash, browser, ملفات) ويوريك كل خطوة في Matrix.",
    "landing.how_3t": "شوف النتيجة",
    "landing.how_3d": "يجيبك بالصوت والصورة، مع ملفات وجداول. كان تحب، يكمّل وحده في الخلفية.",
    "landing.tech_title": "تكنولوجيا وخصوصية",
    "landing.tech_1t": "سحابي آمن",
    "landing.tech_1d": "Gemini 2.0 Flash عبر بوابة مشفّرة على السيرفر — المفتاح ما يخرجش من السيرفر، ما فماش API key في المتصفح ولا في الـ APK.",
    "landing.tech_2t": "يعمل محلي زادة",
    "landing.tech_2d": "كان السيرفر طايح، جينيو يكمّل على الجهاز (Tier A) — ما يوقفش.",
    "landing.tech_3t": "صوت وصورة",
    "landing.tech_3d": "تعرّف على الصوت بالدارجة (ar-TN) وجهاً لوجه مع تتبّع الوجه. خصوصيتك محفوظة: الميكروفون والكاميرا بإذنك فقط.",
    "landing.tech_4t": "كود مفتوح وقابل للتوسيع",
    "landing.tech_4d": "أدوات جديدة، سكربتات، وحتى أصوات — كل شيء قابل للتخصيص.",
    "landing.road_title": "خارطة الطريق — 4 مراحل",
    "landing.road_1p": "المرحلة 1",
    "landing.road_1t": "Academy — كورسات الأشباح + معلّم Genio",
    "landing.road_1d": "كورسات مسجّلة خفية + جينيو يشرح، يسأل، ويصحّح — كأنّك مع أستاذ خاص 24/24.",
    "landing.road_2p": "المرحلة 2",
    "landing.road_2t": "Education Edition — شرح ومراجعة بالدارجة",
    "landing.road_2d": "دروس ابتدائي وثانوي وجامعة بالدارجة التونسية — تلخيص، تمارين، ومراجعة ذكية.",
    "landing.road_3p": "المرحلة 3",
    "landing.road_3t": "SysAdmin — Docker + VPN + سكربتات أتمتة",
    "landing.road_3d": "إدارة سيرفرات، حاويات، شبكات وVPN بضغطة — جينيو يكتب وينفّذ السكربتات.",
    "landing.road_4p": "المرحلة 4",
    "landing.road_4t": "Daily Automation — n8n + أجهزة ذكية + صوت متنقّل",
    "landing.road_4d": "أتمتة يومية: n8n، منزل ذكي، أوامر صوتية وانت في الطريق.",
    "landing.founder_title": "المؤسس — محمد عزمي كعنيش",
    "landing.founder_body": "خبير بنية تحتية وأتمتة — سنين خبرة في Docker، الشبكات، وVPN. هدفه كسر الحاجز بين التونسي والتكنولوجيا: جينيو معمول باش أي تونسي — تلميذ، حرفي، مهندس — ينجم يستعمل الذكاء الاصطناعي بلغته، بثقته، وبطريقته.",
    "landing.founder_more": "اقرا أكثر →",
    "landing.platform_title": "وين تنجّم تستعمل جينيو؟",
    "landing.platform_linux": "Linux (AppImage / DEB)",
    "landing.platform_linux_ok": "✅ متوفر — v5.0.0",
    "landing.platform_docker": "Docker",
    "landing.platform_docker_ok": "✅ متوفر",
    "landing.platform_other": "Windows / macOS / Android / iOS",
    "landing.platform_other_no": "❌ غير متوفر حالياً",
    "landing.platform_os": "HiTech-OS",
    "landing.platform_os_soon": "عقد جاهز — التنفيذ لاحقاً",
    "landing.platform_all": "كل خيارات التحميل ←",
    "landing.install_title": "ثبّت جينيو في 3 خطوات",
    "landing.install_1t": "حمّل",
    "landing.install_1d": "الأرشيف +-checksum من صفحة v5.0.0",
    "landing.install_2t": "ثبّت",
    "landing.install_2d": "بالـ CLI أو AppImage — الـ doctor يتأكد",
    "landing.install_3t": "تحقّق",
    "landing.install_3d": "genio doctor → HEALTHY (0 FAIL)",
    "landing.install_more": "مساعد التثبيت ←",
    "landing.footer_made": "جينيو — صُنع في تونس 🇹🇳 بكل حب",
    "landing.footer_rights": "خصوصيتك أولويتنا",
    "landing.footer_enter": "ادخل",
    "landing.footer_about": "من نحن",
    "landing.alt_hero": "Genio Hero — Jebba rouge",
    "landing.alt_founder": "محمد عزمي كعنيش",
    // install.* (install assistant — commands stay exact, prose localized)
    "install.page_title": "التثبيت",
    "install.title": "ثبّت Genio",
    "install.sub": "وضع المعاينة / التوثيق: الصفحة هاذي ترشدك لتثبيت حقيقي — هي بيدها ما تثبّت شيء. كل حالة تعكس ماكينة التثبيت الحقيقية.",
    "install.platform_card": "المنصة المكتشفة",
    "install.platform_line": "المنصة المكتشفة (على جهازك فقط، ما يتبعث شيء):",
    "install.cmd_install": "أمر التثبيت",
    "install.cmd_docker": "أمر docker",
    "install.understood": "مفهومة",
    "install.pending": "تستنى",
    "install.mark_pending": "رجّعها تستنى",
    "install.mark_understood": "علّمها مفهومة",
    "install.reset": "صفّر",
    "install.gotit": "فهمت",
    "install.viz_title": "شوف log حقيقي للمثبّت (الصق ناتج --json-events)",
    "install.viz_help": "نفّذ genio install --json-events … في الترمينال، والصق الناتج هنا. الحالات تترسم من الأحداث الحقيقية — السطور الغالطة تتعلّم، ما تتخباش.",
    "install.viz_log_label": "سجل أحداث المثبّت",
    "install.viz_render": "ارسم الخط الزمني",
    "install.viz_empty": "السجل فارغ — ما ترسم شيء (بصراحة).",
    "install.viz_invalid": "سطر غالط:",
    "install.viz_recovery": "الإصلاح:",
    "install.viz_docs": "الوثائق ←",
    "install.viz_timeline": "الخط الزمني لأحداث المثبّت",
    "install.help_title": "تحقّق، صلّح، اطلب العون (أوامر حقيقية)",
    "install.code_verify": "تحقّق",
    "install.code_repair": "إصلاح",
    "install.code_rollback": "تراجع",
    "install.go_download": "مركز التحميل",
    "install.go_docs": "وثائق التثبيت",
    "install.state_detecting_label": "تعرّف على الجهاز",
    "install.state_detecting_desc": "نستكشف النظام والعتاد والأدوات والمنافذ والتثبيتات الموجودة.",
    "install.state_checking_label": "فحوصات قبل التثبيت",
    "install.state_checking_desc": "نتحقق من المتطلبات قبل أي تغيير.",
    "install.state_ready_label": "جاهز",
    "install.state_ready_desc": "الجهاز جاهز؛ نستنى تأكيدك.",
    "install.state_downloading_label": "التحميل",
    "install.state_downloading_desc": "نجيبو ملف النسخة. بايتات حقيقية فقط.",
    "install.state_verifying_label": "التحقق من السلامة",
    "install.state_verifying_desc": "نتحقق من SHA-256 (والتوقيع كي يتوفر). أي اختلاف يوقّف كل شيء.",
    "install.state_installing_label": "التثبيت",
    "install.state_installing_desc": "فكّ الضغط، إنشاء venv، تثبيت الاعتماديات المثبتة.",
    "install.state_configuring_label": "الإعداد",
    "install.state_configuring_desc": "كتابة الإعدادات والمنافذ والبيئة (الأسرار عمرها ما تظهر في السجلات).",
    "install.state_securing_label": "التأمين",
    "install.state_securing_desc": "صلاحيات الملفات، فحص الإقلاع، السحاب مسكّر افتراضياً.",
    "install.state_health_check_label": "فحص الصحة",
    "install.state_health_check_desc": "تحقق من الاستيراد، اختبار API، اختبار العزل. العمليات الحية وحدها ما تكفيش.",
    "install.state_complete_label": "جاهز",
    "install.state_complete_desc": "التثبيت تم والتحقق سليم.",
    // download.* (download center — commands/URLs stay exact)
    "download.page_title": "التحميل",
    "download.title": "حمّل Genio",
    "download.sub": "النسخة {v}. المنصة المكتشفة: {p} (تختار بيدك ديما).",
    "download.available": "متوفّر",
    "download.unavailable": "موش متوفّر",
    "download.cmd": "أمر التثبيت",
    "download.why_unavailable": "البناء موش متوفّر توا — {r}. ما فماش زر تحميل وهمي.",
    "download.release": "النسخة {t}",
    "download.manifest": "ملف النسخة",
    "download.sbom": "SBOM",
    // security.* (security center — proofs stay exact file/command identifiers)
    "security.page_title": "الأمان",
    "security.title": "مركز الأمان",
    "security.sub": "كل ادعاء مربوط باختبار ولا تدقيق ولا تنفيذ. حتى شيء هنا ما يعني «آمن 100%».",
    "security.details": "التفاصيل والدليل",
    "security.proof": "الدليل:",
    "security.tag_verified": "متنفّذ + متحقق منو",
    "security.tag_conditional": "مشروط",
    "security.tag_pending": "يستنى",
    "security.tag_pending_gated": "يستنى — يتقفل في 5.0",
    "security.sandbox.title": "عزل fail-closed",
    "security.sandbox.body": "الوضع الصارم من غير Docker يرفض تنفيذ أي شيء على الجهاز (rc 125، SANDBOX_UNAVAILABLE). مثبت حي في التطوير والتثبيتات والحاويات.",
    "security.policy.title": "محرك السياسات",
    "security.policy.body": "كل عملية تتعدى على بوابة مركزية ALLOW/DENY/ESCALATE. العمليات الخطيرة تستحق تأكيد.",
    "security.filesystem.title": "حدود نظام الملفات",
    "security.filesystem.body": "التصريح يصير بعد التطبيع بالمسار الحقيقي (الروابط الرمزية و.. و/etc والأجهزة محظورة).",
    "security.bash.title": "Bash منظّم",
    "security.bash.body": "20 صنف أوامر متحقق منها بنيوياً (الحقن، الاستبدال، المفسرات، fork bombs).",
    "security.ssrf.title": "مضاد SSRF للمتصفح",
    "security.ssrf.body": "الـ IP الخاصة وlocalhost ونقاط الميتاداتا وإعادة ربط DNS محظورة fail-closed.",
    "security.upload.title": "التحقق من الرفع",
    "security.upload.body": "البصمة السحرية (عمرها ما تكون MIME العميل)، حصة 50MB، صلاحية ساعة، تخزين 0o600.",
    "security.auth.title": "توثيق API",
    "security.auth.body": "Bearer قصير العمر (HMAC 15 دقيقة)، حدود معدل، والإقلاع الصارم/الإنتاجي يرفض العمل من غير مفتاح.",
    "security.killswitch.title": "زر القتل",
    "security.killswitch.body": "إيقاف استباقي يشمل العمليات الفرعية؛ إعادة التسلح ديما صريحة.",
    "security.telemetry.title": "تنظيف التليميتري",
    "security.telemetry.body": "المفاتيح والرموز والكوكيز والأسرار تتنظف؛ التليميتري تبقى مفيدة.",
    "security.ipc.title": "أمان IPC",
    "security.ipc.body": "توثيق نفس الـ UID (الـ localhost موش موثوق)، nonce ضد إعادة التشغيل، حد معدل، وتدقيق كامل.",
    "security.container.title": "تحصين الحاويات",
    "security.container.body": "مستخدم غير جذري، HEALTHCHECK، اعتماديات مثبتة، ما فماش أسرار في الطبقات.",
    "security.release.title": "سلامة النسخ",
    "security.release.body": "أرشيفات مرقمة + SHA-256 + ملفات تعريف متحقق منها fail-closed (مختبرة ضد العبث).",
    "security.cloud.title": "توجيه السحاب",
    "security.cloud.body": "خلفيات السحاب تبقى معطلة إلا إذا فعّلت GENIO_ALLOW_CLOUD صراحة.",
    "security.voice.title": "خدمة الصوت",
    "security.voice.body": "VODER خارجي؛ أخطاء 422/400 صريحة، ما فماش 500 صامت ولا يتامى.",
    "security.admin.title": "صفحة الإدارة",
    "security.admin.body": "صفحة /genio/admin توا من غير بوابة توثيق. لازم تطلب مفتاح API من المستخدم متحقق منو ضد الباكند قبل عرض الإحصائيات الداخلية.",
    "security.edge.title": "حافة الإنتاج",
    "security.edge.body": "الترافيك العام توا يوصل لسيرفرات التطوير (vite preview + uvicorn مباشر). تدقيق CSP/الترويسات مبرمج.",
    // explore.* (architecture explorer — identifiers/paths stay exact)
    "explore.page_title": "استكشف",
    "explore.title": "كيفاش يخدم Genio",
    "explore.sub": "انقر على أي مجال باش تشوف الغرض والحدود والحالة الصادقة. المجالات المحظورة عمرها ما تبان جاهزة.",
    "explore.purpose": "الغرض والحدود",
    "explore.what": "شنوّة:",
    "explore.boundary": "الحد:",
    "explore.docs": "التوثيق ←",
    "explore.go_security": "مركز الأمان",
    "explore.go_api": "مستكشف API",
    "explore.status_production": "إنتاج",
    "explore.status_conditional": "مشروط",
    "explore.status_desktop": "محظور — ما فماش Rust toolchain هنا",
    "explore.status_mobile": "محظور — التوقيع خارجي",
    "explore.status_hitechos": "العقد جاهز / التنفيذ يستنى",
    "explore.agent.what": "تنفيذ مهمات متعددة الخطوات (≤5 تكرارات، ميزانيات مفروضة).",
    "explore.agent.boundary": "كل خطوة تتعدى على السياسة؛ الأدوات بقائمة بيضاء.",
    "explore.policy.what": "بوابة مركزية ALLOW / DENY / ESCALATE لكل عملية.",
    "explore.policy.boundary": "السياسة تعيش في Genio؛ النظام والواجهة يطلبو فقط.",
    "explore.router.what": "محلي ← Ollama ← HiTech-OS ← سحاب (opt-in صريح).",
    "explore.router.boundary": "السحاب مسكّر افتراضياً؛ ما فماش نقل بيانات صامت.",
    "explore.memory.what": "تذكّر الجلسات مع بيانات تدقيق وحماية من التسميم.",
    "explore.memory.boundary": "عزل لكل جلسة؛ المصدر متتبع.",
    "explore.tools.what": "Bash (منظّم)، نظام ملفات (محدود)، متصفح، استعمال الحاسوب.",
    "explore.tools.boundary": "كل أداة عندها قدرة + سياسة + تدقيق.",
    "explore.sandbox.what": "حاويات Docker، حصص، نظام ملفات للقراءة. Fail-closed.",
    "explore.sandbox.boundary": "فشل العزل = ما فماش تنفيذ على المضيف، ديما.",
    "explore.ipc.what": "عقد UDS: hello/capabilities/infer، أخطاء، أحداث.",
    "explore.ipc.boundary": "توثيق نفس UID، nonce، حد معدل، تدقيق.",
    "explore.installer.what": "ملفات تعريف، نسخ احتياطي، إصلاح/تحديث/تراجع، doctor.",
    "explore.installer.boundary": "عمره ما يحذف بيانات المستخدم بصمت؛ التأكيدات مطلوبة.",
    "explore.docker.what": "صورة محصنة: غير جذري، HEALTHCHECK، اعتماديات مثبتة.",
    "explore.docker.boundary": "ما فماش أسرار في الطبقات؛ سوكيت Docker كان عند الحاجة للعزل.",
    "explore.models.what": "Ollama محلي (gemma4:12b مقيم)؛ حالات UNAVAILABLE صريحة.",
    "explore.models.boundary": "تزاحم VRAM معلن؛ ما فماش جاهزية وهمية.",
    "explore.voice.what": "STT + VODER TTS (لغة تلقائية؛ 422 صريح غير ذلك).",
    "explore.voice.boundary": "خدمة خارجية؛ تتدهور بصراحة.",
    "explore.desktop.what": "عميل أصلي عبر HTTP API + WS (عقد متحقق منو).",
    "explore.desktop.boundary": "ما فماش أسرار مضمنة؛ ما فماش IPC مميز من الواجهة.",
    "explore.mobile.what": "نفس عقد API؛ تخزين آمن، TLS، وضع متدهور.",
    "explore.mobile.boundary": "توقيع APK يتطلب أسرار النسخة.",
    "explore.hitechos.what": "نظام التشغيل يستهلك Genio عبر IPC؛ الاثنان مستقلان.",
    "explore.hitechos.boundary": "العقد فقط؛ تنفيذ IPC الخادم يستنى جهة النظام.",
    // api.* (API explorer — paths/summaries stay technical, chrome localized)
    "api.page_title": "API",
    "api.title": "مستكشف API",
    "api.sub": "مشتق من schemas/openapi-genio.json ({n} مسارات) مع مسار WebSocket (مو جزء من OpenAPI بطبيعته). التوثيق: ترويسة مفتاح API ولا Bearer قصير العمر عند الحاجة. المستكشف للقراءة فقط — ما فماش وحدة تحكم حية.",
    "api.ws_note": "بث الأوامر: ابعث {action:'prompt', text} ← استقبل إطارات stats/answer. نفس نموذج التوثيق كـ HTTP.",
    "api.details": "التفاصيل",
    "api.no_summary": "شوف مخطط OpenAPI",
    "api.auth_line": "التوثيق: حسب الـ endpoint (شوف docs/API.md). الأخطاء: HTTP قياسي + JSON منظف.",
    // docs.* (docs viewer chrome — doc bodies stay as authored)
    "docs.page_title": "الوثائق",
    "docs.title": "التوثيق",
    "docs.sub": "منتقى من docs/ وقت البناء. مختبر مع Genio 4.1.0.",
    "docs.search_label": "ابحث في التوثيق",
    "docs.search_ph": "ابحث في الوثائق…",
    "docs.source": "المصدر:",
    "docs.empty": "ما فماش توثيق يطابق.",
    "docs.crumb": "الوثائق",
    "docs.not_found": "الوثيقة موش موجودة.",
    "docs.tested_with": "مختبر مع Genio 4.1.0 · المصدر:",
    // auth.*
    "auth.title": "أهلا بيك في Genio",
    "auth.subtitle": "باش تبدأ تحكي معايا، ادخل بحساب Google ولا كمّل من غير حساب.",
    "auth.why": "الدخول يخوّلك تستعمل السحاب. من غير دخول تنجم تستعمل Genio على جهازك.",
    "auth.google": "ادخل بـ Google",
    "auth.continue_google": "كمّل بـ Google",
    "auth.continue": "كمّل",
    "auth.skip": "كمّل من غير حساب",
    "auth.signed_in": "داخل توا — انقر كمّل",
    "auth.agree": "بمواصلتك انت توافق على استعمال Genio. المفتاح يتخزن كان في جهازك.",
    "auth.checking": "نتحققو...",
    // shell.* (unified L1 + panels)
    "shell.ready": "Genio حاضر",
    "shell.greeting": "عسلامة! أنا Genio",
    "shell.listening": "Genio يسمع فيك",
    "shell.understanding": "Genio قاعد يفهم في طلبك",
    "shell.thinking": "Genio يخمّم",
    "shell.planning": "Genio يخطط",
    "shell.explaining": "Genio يجاوب فيك",
    "shell.executing": "Genio قاعد يخدم على مهمّتك",
    "shell.waiting": "Genio يستنى",
    "shell.asking": "Genio يستنى في ردّك",
    "shell.success": "كمّلت المهمّة",
    "shell.warning": "رد بالك، فما حاجة",
    "shell.error": "صار مشكل",
    "shell.recovering": "Genio قاعد يصلّح",
    "shell.celebrating": "برافو، كمّلت!",
    "shell.sleeping": "Genio راقد",
    "shell.disconnected": "تقطع الاتصال",
    "shell.attention": "Genio يحب انتباهك",
    "shell.current_task": "المهمّة الحالية",
    "shell.no_task": "ما فماش مهمّة. ابعث رسالة باش تبدأ.",
    "shell.resources": "الموارد",
    "shell.details": "تفاصيل تقنية",
    "shell.result": "النتيجة",
    "shell.events": "الأحداث",
    "shell.cancel": "ألغي",
    "shell.reconnect": "عاود الاتصال",
    "shell.unavailable": "غير متوفّر",
    "shell.offline": "ما فماش اتصال — الوثائق والإعدادات والتفضيلات تخدم. الذكاء الاصطناعي يحتاج اتصال.",
    "shell.connection_lost": "تقطع الاتصال",
    "shell.details_docs": "تفاصيل في الوثائق",
    "shell.advanced_on": "متقدّم مفعّل",
    "shell.opt_in": "اختياري",
    "shell.hide_advanced": "خبّي المتقدّم",
    "shell.show_advanced": "وريني المتقدّم",
    // input.*
    "input.placeholder": "ابعث لـ Genio… (Enter باش تبعث، Shift+Enter باش تدخل سطر جديد)",
    "input.attach": "رفق ملفّات",
    "input.mic": "اسمع",
    "input.stop": "وقّف التسجيل",
    "input.recording": "جاري التسجيل",
    "input.send": "ابعث",
    "input.cancel": "ألغي",
    "input.drop": "حطّ ملفّات هنا باش ترفقهم",
    "input.listening": "Genio يسمع فيك — احكي توا",
    "input.listen": "اسمع",
    "input.listen_label": "اسمع",
    "input.stop_recording": "وقّف التسجيل",
    "input.live_transcription": "كلّم… التحويل الحيّ يشتغل",
    "input.release_to_send": "حرّر باش تبعث عبر Web Audio",
    "input.send_label": "جاهز",
    // errors.*
    "errors.generic": "صار مشكل غير متوقع. عاود جرّب، ولو تكرر ابعث التفاصيل.",
    "errors.network": "ما فماش اتصال. تحقق من الإنترنت وعاود جرّب.",
    "errors.auth": "لازم الدخول باش تكمّل. ادخل ولا كمّل من غير حساب.",
    "errors.mic": "المايكرو ما لقاهش",
    "errors.server": "السيرفر ما جاوبش. عاود جرّب بعد شوية.",
    "errors.timeout": "طوّل برشا وما جاش رد. عاود جرّب.",
    "errors.tech_details": "تفاصيل تقنية",
    "errors.cloud_auth": "سجّل بـ Google باش تكمّل في السحاب",
    "errors.cloud_fail": "مشكل في الاتصال بالسحاب — عاود جرّب",
    "errors.cloud_retry": "عاود جرّب",
    "errors.google_signin": "ادخل بـ Google",
    "errors.mic_unavailable": "المايكرو موش متوفّر. تحقق من إذن المتصفح.",
    "errors.google_auth_failed": "الدخول بـ Google فشل. عاود جرّب.",
    "errors.recording": "جاري التسجيل",
    "errors.live_transcription": "التحويل الحيّ يشتغل…",
    "errors.release_to_send": "حرّر باش تبعث",
    "errors.close_chat": "سكّر الدردشة",
    "errors.open_chat": "افتح الدردشة",
    // status.*
    "status.connected": "متصل",
    "status.connecting": "قاعد يتصل...",
    "status.disconnected": "مقطوع",
    "status.ready": "حاضر",
    "status.working": "قاعد يخدم",
    "status.done": "كمّل",
    // task.*
    "task.title": "المهمّة الحالية",
    "task.step": "الخطوة الحالية",
    "task.steps": "الخطوات",
    "task.tool": "الأداة",
    "task.duration": "المدة",
    "task.status": "الحالة",
    "task.cancel": "ألغي المهمّة",
    "task.cancel_requested": "طلب الإلغاء تبعث، نستنى التأكيد...",
    "task.cancelled": "تلغات المهمّة",
    "task.queued": "في الانتظار",
    "task.running": "قاعدة تخدم",
    "task.waiting": "تستنى",
    "task.completed": "كمّلت",
    "task.failed": "فشلت",
    "task.elapsed": "المدة (محسوبة في جهازك)",
    // settings.*
    "settings.density": "الكثافة المعرفية",
    "settings.ambient": "المؤثّرات المحيطة",
    // density.*
    "density.simple": "بسيط",
    "density.detailed": "مفصّل",
    "density.advanced": "متقدّم",
    // ambient.*
    "ambient.glow": "توهّج/جسيمات",
    "ambient.reduced": "تقليل الحركة",
    "ambient.note": "تنبيهات الأمان وحالة المهمّة والأخطاء ما تتطفاش أبدا بالإعدادات هاذي.",
    // events.*
    "events.empty": "ما فماش أحداث توا.",
    // tool.*
    "tool.activity": "نشاط الأدوات",
    "tool.evidence_unavailable": "ما فماش دليل متوفّر",
    // a11y.*
    "a11y.skip": "تخطى للمحتوى",
    "a11y.nav_dialog": "التنقل",
    "a11y.open_menu": "افتح قائمة التنقل",
    "a11y.close": "سكّر",
    "a11y.menu": "افتح القائمة",
    "a11y.copy": "انسخ الأمر",
    "a11y.copied": "تنسخ ✓",
    // onboarding.*
    "onboarding.welcome": "مرحبا بيك في Genio",
    "onboarding.start": "إبدا",
    "onboarding.skip": "تخطى",
    // permissions.*
    "perm.checking": "نتحقّقو من إمكانيّات الجهاز...",
    "perm.title": "الأذونات والعتاد",
    "perm.subtitle": "Genio يحتاج برشا أذونات باش يخدم ممتاز على الأندرويد",
    "perm.camera": "الكاميرا",
    "perm.camera_desc": "تتبّع الوجه بالكاميرا الأمامية (ابتسامة الشاشة)",
    "perm.microphone": "المايكرو",
    "perm.microphone_desc": "إدخال الصوت بالتونسي (تحويل الكلام لنصّ)",
    "perm.storage": "التخزين",
    "perm.storage_desc": "الملفّات المرفقة وقراءة الوسائط",
    "perm.network": "الشبكة",
    "perm.network_desc": "الاتصال بالإنترنت",
    "perm.grant_all": "أذن لكلّ",
    "perm.reverify": "عاود التحقّق",
    "perm.continue_anyway": "كمّل من غير أذونات",
    "perm.continue": "كمّل",
    "perm.tauri_note": "أندرويد Tauri يفرض أذونات المانيفست: CAMERA, RECORD_AUDIO, INTERNET, ACCESS_NETWORK_STATE, READ_MEDIA_*.",
    "perm.skip": "تخطّى التأهيل",
    // header.*
    "header.toggle_drawer": "افتح القائمة",
    "header.selfie_mode": "SELFIE MODE",
    "header.toggle_selfie": "تبديل تتبّع الوجه",
    "header.stop": "وقّف",
    "header.disconnect": "تقطع",
    "header.thinking": "خمّم...",
    "header.executing": "ينفّذ: ",
    "header.completed": "كمّل",
    "header.stale": "متوقّف",
    "header.telemetry_paused": "البيانات متوقّفة — السيرفر مشغول",
    // mascot.*
    "mascot.listening": "يسمع...",
    "mascot.speaking": "يحكي...",
    "mascot.tap_to_speak": "اضغط باش تحكي",
    "mascot.gesture_note": "حركات تعلّمها منك",
    "mascot.technical_mode": "الوضع التقني",
    "mascot.mic_start": "احكي مع Genio",
    "mascot.mic_stop": "وقّف المايكرو",
    // telemetry.*
    "telemetry.offline": "🔴 غير متصل",
    "telemetry.thinking": "🟡 جينيو يخمّم...",
    "telemetry.streaming": "🔵 يجاوب",
    "telemetry.ready": "🟢 متصل",
    // app.* (App shell mode buttons + background actions)
    "app.mode_technique": "الوضع التقني",
    "app.mode_mascot": "وضع الماسكوت",
    "app.mode_unified": "الوضع الموحّد",
    "app.mode_mascot_title": "ارجع للماسكوت على كامل الشاشة",
    "app.mode_unified_title": "عرض موحّد: محادثة وحضور ومهمّة",
    "app.kill_agent": "وقّف الوكيل",
    "app.disconnect": "افصل الاتصال",
    // error boundary fallback
    "boundary.crash": "المشهد طاح — وضع الأمان يخدم.",
    "boundary.mascot_crash_hint": "الـ3D ما خدمش على الجهاز هذا — تنجم تكمل عادي بالوضع التقني ولا الموحّد، والدردشة والاتصال يبقاو يخدمو.",
    // permission status values (device messages mapped, never raw English)
    "perm.status_granted": "مسموح",
    "perm.status_online": "متصل",
    "perm.status_offline": "موش متصل",
    "perm.status_denied": "مرفوض — شوف إعدادات الجهاز",
    "perm.status_denied_retry": "مرفوض — تنجم تعاود تطلب",
    "perm.status_unavailable": "غير متوفّر على الجهاز هذا",
    // chat panel (FAB)
    "chat.title": "دردشة Genio",
    "chat.empty": "✨ Genio يسمع — اكتب رسالة ولا احكي ✨",
  },
  fr: {
    nav_home: "Genio",
    nav_explore: "Explorer", nav_security: "Sécurité", nav_docs: "Docs",
    nav_download: "Télécharger", nav_install: "Installer Genio", nav_app: "App",
    install_title: "Installer Genio", try: "Essayer Genio", docs: "Docs",
    offline: "Pas de connexion Internet", error: "Un problème est survenu",
    retry: "Réessayer", task: "Tâche", evidence: "Preuves",
    settings: "Paramètres", assistant: "Assistant", start: "Démarrer",
    tools_activity: "Activité des outils",
    // footer.* (public portal footer)
    "footer.docs": "Docs",
    "footer.security": "Sécurité",
    "footer.api": "API",
    "footer.tag": "souverain • HiTechLab 🇹🇳",
    // landing.* (page d'accueil — le tunisien d'abord, FR secondaire)
    "landing.brand_tag": "Genio",
    "landing.live": "SYSTEM LIVE",
    "landing.founder": "Fondateur",
    "landing.enter_app": "Ouvrir l'app",
    "landing.hero_badge": "Premier compagnon IA tunisien — en Darija",
    "landing.hero_title_a": "Premier compagnon",
    "landing.hero_title_b": "intelligence artificielle",
    "landing.hero_title_c": "tunisien",
    "landing.hero_sub": "Genio vous comprend en Darija, organise votre travail, code, surveille vos serveurs et pilote votre maison connectée — depuis votre téléphone ou votre PC. Confidentialité garantie, local ou cloud selon votre choix.",
    "landing.cta_try": "Essayer Genio →",
    "landing.cta_install": "Installer Genio ↓",
    "landing.cta_how": "Comment ça marche ?",
    "landing.product_explore": "Explorer",
    "landing.product_download": "Télécharger",
    "landing.product_install": "Installation",
    "landing.product_docs": "Docs",
    "landing.product_security": "Sécurité",
    "landing.no_key_note": "Pas de clé API dans le navigateur • hors-ligne Tier A • voix et image",
    "landing.how_title": "Comment ça marche — 3 étapes",
    "landing.how_1t": "Parlez en Darija",
    "landing.how_1d": "Écrivez ou parlez : « organise mon serveur » ou « allume la lumière » — Genio comprend l'arabe, la Darija, le français et l'anglais.",
    "landing.how_2t": "Genio planifie et exécute",
    "landing.how_2d": "Il analyse votre demande, utilise ses outils (bash, browser, fichiers) et montre chaque étape dans Matrix.",
    "landing.how_3t": "Voyez le résultat",
    "landing.how_3d": "Réponse en voix et image, avec fichiers et tableaux. S'il le faut, il continue seul en arrière-plan.",
    "landing.tech_title": "Technologie et confidentialité",
    "landing.tech_1t": "Cloud sécurisé",
    "landing.tech_1d": "Gemini 2.0 Flash via une passerelle chiffrée côté serveur — la clé ne quitte jamais le serveur, aucune clé API ni dans le navigateur ni dans l'APK.",
    "landing.tech_2t": "Fonctionne aussi en local",
    "landing.tech_2d": "Si le serveur tombe, Genio continue sur l'appareil (Tier A) — sans interruption.",
    "landing.tech_3t": "Voix et image",
    "landing.tech_3d": "Reconnaissance vocale en Darija (ar-TN) avec suivi du visage. Votre vie privée est protégée : micro et caméra seulement avec votre accord.",
    "landing.tech_4t": "Code ouvert et extensible",
    "landing.tech_4d": "Nouveaux outils, scripts, et même des voix — tout est personnalisable.",
    "landing.road_title": "Feuille de route — 4 étapes",
    "landing.road_1p": "Étape 1",
    "landing.road_1t": "Academy — cours fantômes + Genio professeur",
    "landing.road_1d": "Cours enregistrés + Genio explique, interroge et corrige — comme un prof particulier 24h/24.",
    "landing.road_2p": "Étape 2",
    "landing.road_2t": "Education Edition — explications et révisions en Darija",
    "landing.road_2d": "Primaire, secondaire et université en Darija tunisienne — résumés, exercices et révision intelligente.",
    "landing.road_3p": "Étape 3",
    "landing.road_3t": "SysAdmin — Docker + VPN + scripts d'automatisation",
    "landing.road_3d": "Serveurs, conteneurs, réseaux et VPN en un clic — Genio écrit et exécute les scripts.",
    "landing.road_4p": "Étape 4",
    "landing.road_4t": "Daily Automation — n8n + objets connectés + voix mobile",
    "landing.road_4d": "Automatisation quotidienne : n8n, maison connectée, commandes vocales en route.",
    "landing.founder_title": "Fondateur — Mohamed Azmi Kaanich",
    "landing.founder_body": "Expert infrastructure et automatisation — des années en Docker, réseaux et VPN. Son but : briser la barrière entre le Tunisien et la technologie : Genio est fait pour que tout Tunisien — élève, artisan, ingénieur — utilise l'IA dans sa langue, en confiance, à sa façon.",
    "landing.founder_more": "En savoir plus →",
    "landing.platform_title": "Où utiliser Genio ?",
    "landing.platform_linux": "Linux (AppImage / DEB)",
    "landing.platform_linux_ok": "✅ Disponible — v5.0.0",
    "landing.platform_docker": "Docker",
    "landing.platform_docker_ok": "✅ Disponible",
    "landing.platform_other": "Windows / macOS / Android / iOS",
    "landing.platform_other_no": "❌ Indisponible pour le moment",
    "landing.platform_os": "HiTech-OS",
    "landing.platform_os_soon": "Contrat prêt — implémentation à venir",
    "landing.platform_all": "Toutes les options ←",
    "landing.install_title": "Installez Genio en 3 étapes",
    "landing.install_1t": "Télécharger",
    "landing.install_1d": "L'archive + checksum depuis la page v5.0.0",
    "landing.install_2t": "Installer",
    "landing.install_2d": "Via CLI ou AppImage — le doctor vérifie",
    "landing.install_3t": "Vérifier",
    "landing.install_3d": "genio doctor → HEALTHY (0 FAIL)",
    "landing.install_more": "Assistant d'installation ←",
    "landing.footer_made": "Genio — fait en Tunisie 🇹🇳 avec amour",
    "landing.footer_rights": "votre vie privée d'abord",
    "landing.footer_enter": "Entrer",
    "landing.footer_about": "Qui sommes-nous",
    "landing.alt_hero": "Genio Hero — Jebba rouge",
    "landing.alt_founder": "Mohamed Azmi Kaanich",
    // install.* (assistant d'installation — commandes exactes, prose localisée)
    "install.page_title": "Installation",
    "install.title": "Installer Genio",
    "install.sub": "Mode aperçu / documentation : cette page guide une installation réelle — elle n'installe rien elle-même. Chaque état reflète la vraie machine d'installation.",
    "install.platform_card": "Plateforme détectée",
    "install.platform_line": "Plateforme détectée (côté client uniquement, rien n'est transmis) :",
    "install.cmd_install": "commande d'installation",
    "install.cmd_docker": "commande docker",
    "install.understood": "COMPRIS",
    "install.pending": "EN ATTENTE",
    "install.mark_pending": "Remettre en attente",
    "install.mark_understood": "Marquer comme compris",
    "install.reset": "réinitialiser",
    "install.gotit": "compris",
    "install.viz_title": "Visualiser un vrai log d'installation (collez --json-events)",
    "install.viz_help": "Exécutez genio install --json-events … dans votre terminal, collez la sortie ici. Les états viennent des vrais événements — les lignes invalides sont signalées, jamais cachées.",
    "install.viz_log_label": "Journal d'événements de l'installateur",
    "install.viz_render": "Afficher la chronologie",
    "install.viz_empty": "Journal vide — rien à afficher (honnêtement).",
    "install.viz_invalid": "LIGNE INVALIDE :",
    "install.viz_recovery": "Réparation :",
    "install.viz_docs": "Docs ←",
    "install.viz_timeline": "Chronologie des événements",
    "install.help_title": "Vérifier, réparer, obtenir de l'aide (vraies commandes)",
    "install.code_verify": "vérifier",
    "install.code_repair": "réparer",
    "install.code_rollback": "annuler",
    "install.go_download": "Centre de téléchargement",
    "install.go_docs": "Docs d'installation",
    "install.state_detecting_label": "Détection du système",
    "install.state_detecting_desc": "Exploration OS, matériel, outils, ports et installations existantes.",
    "install.state_checking_label": "Vérifications préalables",
    "install.state_checking_desc": "Validation des prérequis avant tout changement.",
    "install.state_ready_label": "Prêt",
    "install.state_ready_desc": "Système prêt ; en attente de votre confirmation.",
    "install.state_downloading_label": "Téléchargement",
    "install.state_downloading_desc": "Récupération de l'artefact. Que des octets réels.",
    "install.state_verifying_label": "Vérification d'intégrité",
    "install.state_verifying_desc": "SHA-256 (et signature si disponible) vérifiés. Écart = arrêt.",
    "install.state_installing_label": "Installation",
    "install.state_installing_desc": "Extraction, venv, dépendances épinglées.",
    "install.state_configuring_label": "Configuration",
    "install.state_configuring_desc": "Config, ports et environnement (jamais de secrets dans les logs).",
    "install.state_securing_label": "Sécurisation",
    "install.state_securing_desc": "Permissions, contrôle de démarrage, cloud fermé par défaut.",
    "install.state_health_check_label": "Contrôle de santé",
    "install.state_health_check_desc": "Vérif import, sonde API, sonde sandbox. Un processus vivant ne suffit pas.",
    "install.state_complete_label": "Prêt",
    "install.state_complete_desc": "Installation vérifiée saine.",
    // download.* (centre de téléchargement — commandes/URLs exactes)
    "download.page_title": "Téléchargement",
    "download.title": "Télécharger Genio",
    "download.sub": "Version {v}. Plateforme détectée : {p} (choix manuel toujours possible).",
    "download.available": "DISPONIBLE",
    "download.unavailable": "INDISPONIBLE",
    "download.cmd": "commande d'installation",
    "download.why_unavailable": "Build indisponible — {r}. Aucun faux bouton affiché.",
    "download.release": "Version {t}",
    "download.manifest": "Manifeste de version",
    "download.sbom": "SBOM",
    // security.* (centre de sécurité — preuves = identifiants exacts)
    "security.page_title": "Sécurité",
    "security.title": "Centre de sécurité",
    "security.sub": "Chaque affirmation est liée à un test, un audit ou une implémentation. Rien ici ne signifie « 100 % sécurisé ».",
    "security.details": "Détails et preuves",
    "security.proof": "Preuve :",
    "security.tag_verified": "IMPLÉMENTÉ + VÉRIFIÉ",
    "security.tag_conditional": "CONDITIONNEL",
    "security.tag_pending": "EN ATTENTE",
    "security.tag_pending_gated": "EN ATTENTE — verrouillé en 5.0",
    "security.sandbox.title": "Sandbox fail-closed",
    "security.sandbox.body": "Le mode strict sans Docker refuse toute exécution hôte (rc 125, SANDBOX_UNAVAILABLE). Prouvé en dev, installs et conteneurs.",
    "security.policy.title": "Moteur de politiques",
    "security.policy.body": "Chaque action passe une porte centrale ALLOW/DENY/ESCALATE. Les opérations destructrices exigent confirmation.",
    "security.filesystem.title": "Frontière filesystem",
    "security.filesystem.body": "Autorisation après canonisation realpath (symlinks, .., /etc, périphériques bloqués).",
    "security.bash.title": "Bash structuré",
    "security.bash.body": "20 classes de commandes validées structurellement (injection, substitution, interpréteurs, fork bombs).",
    "security.ssrf.title": "Anti-SSRF navigateur",
    "security.ssrf.body": "IP privées, localhost, endpoints metadata et DNS-rebinding bloqués en fail-closed.",
    "security.upload.title": "Validation d'upload",
    "security.upload.body": "Magic bytes (jamais le MIME client), quota 50 Mo, TTL 1h, stockage 0o600.",
    "security.auth.title": "Authentification API",
    "security.auth.body": "Bearer courte durée (HMAC 15 min), rate limits, le boot strict/prod refuse sans clé.",
    "security.killswitch.title": "Kill switch",
    "security.killswitch.body": "Arrêt préemptif incl. processus enfants ; réarmement toujours explicite.",
    "security.telemetry.title": "Nettoyage télémétrie",
    "security.telemetry.body": "Clés, tokens, cookies et secrets nettoyés ; télémétrie toujours utile.",
    "security.ipc.title": "Sécurité IPC",
    "security.ipc.body": "Auth même UID (localhost non fiable), nonce anti-rejeu, rate limit, audit complet.",
    "security.container.title": "Durcissement conteneurs",
    "security.container.body": "Utilisateur non-root, HEALTHCHECK, dépendances épinglées, aucun secret dans les couches.",
    "security.release.title": "Intégrité des versions",
    "security.release.body": "Archives versionnées + SHA-256 + manifestes vérifiés fail-closed (testé anti-falsification).",
    "security.cloud.title": "Routage cloud",
    "security.cloud.body": "Backends cloud désactivés sauf si GENIO_ALLOW_CLOUD est explicitement défini.",
    "security.voice.title": "Service vocal",
    "security.voice.body": "VODER externe ; erreurs 422/400 honnêtes, pas de 500 silencieux ni d'orphelins.",
    "security.admin.title": "Page admin",
    "security.admin.body": "/genio/admin n'a actuellement aucune porte d'auth. Elle doit exiger une clé API fournie par l'utilisateur et vérifiée contre le backend avant d'afficher les stats internes.",
    "security.edge.title": "Bordure de production",
    "security.edge.body": "Le trafic public termine actuellement sur des serveurs de dev (vite preview + uvicorn direct). Audit CSP/headers planifié.",
    // explore.* (explorateur d'architecture — identifiants/chemins exacts)
    "explore.page_title": "Explorer",
    "explore.title": "Comment Genio fonctionne",
    "explore.sub": "Cliquez sur un domaine pour le but, les limites et le statut honnête. Les domaines bloqués n'ont jamais l'air prêts.",
    "explore.purpose": "But et limites",
    "explore.what": "Quoi :",
    "explore.boundary": "Limite :",
    "explore.docs": "Documentation ←",
    "explore.go_security": "Centre de sécurité",
    "explore.go_api": "Explorateur API",
    "explore.status_production": "PRODUCTION",
    "explore.status_conditional": "CONDITIONNEL",
    "explore.status_desktop": "BLOQUÉ — pas de toolchain Rust ici",
    "explore.status_mobile": "BLOQUÉ — signature externe",
    "explore.status_hitechos": "CONTRAT PRÊT / IMPL EN ATTENTE",
    "explore.agent.what": "Exécution multi-étapes (≤5 itérations, budgets imposés).",
    "explore.agent.boundary": "Chaque étape passe la politique ; outils en liste blanche.",
    "explore.router.what": "local → Ollama → HiTech-OS → cloud (opt-in explicite).",
    "explore.router.boundary": "Cloud fermé par défaut ; aucun transfert silencieux.",
    "explore.policy.what": "Porte centrale ALLOW / DENY / ESCALATE pour chaque action.",
    "explore.policy.boundary": "La politique vit dans Genio ; OS et UI ne font que demander.",
    "explore.memory.what": "Rappel de session avec métadonnées d'audit et gardes anti-poison.",
    "explore.memory.boundary": "Isolation par session ; provenance suivie.",
    "explore.tools.what": "Bash (structuré), filesystem (borné), navigateur, computer-use.",
    "explore.tools.boundary": "Chaque outil a capacité + politique + audit.",
    "explore.sandbox.what": "Conteneurs Docker, quotas, FS lecture seule. Fail-closed.",
    "explore.sandbox.boundary": "Échec sandbox = aucune exécution hôte, toujours.",
    "explore.ipc.what": "Contrat UDS : hello/capabilities/infer, erreurs, événements.",
    "explore.ipc.boundary": "Auth même UID, nonce, rate-limit, audit.",
    "explore.installer.what": "Manifestes, sauvegardes, repair/update/rollback, doctor.",
    "explore.installer.boundary": "Ne supprime jamais les données sans confirmation.",
    "explore.docker.what": "Image durcie : non-root, HEALTHCHECK, dépendances épinglées.",
    "explore.docker.boundary": "Aucun secret dans les couches ; socket seulement si sandbox requis.",
    "explore.models.what": "Ollama local (gemma4:12b résident) ; états UNAVAILABLE honnêtes.",
    "explore.models.boundary": "Contention VRAM déclarée ; pas de fausse disponibilité.",
    "explore.voice.what": "STT + VODER TTS (langue auto ; 422 explicite sinon).",
    "explore.voice.boundary": "Service externe ; dégradation honnête.",
    "explore.desktop.what": "Client natif via HTTP API + WS (contrat validé).",
    "explore.desktop.boundary": "Aucun secret embarqué ; pas d'IPC privilégié depuis l'UI.",
    "explore.mobile.what": "Même contrat API ; stockage sécurisé, TLS, mode dégradé.",
    "explore.mobile.boundary": "La signature APK exige les secrets de release.",
    "explore.hitechos.what": "L'OS consomme Genio via IPC ; les deux restent indépendants.",
    "explore.hitechos.boundary": "Contrat uniquement ; implémentation IPC côté OS en attente.",
    // api.* (explorateur API — chemins/résumés techniques, chrome localisé)
    "api.page_title": "API",
    "api.title": "Explorateur API",
    "api.sub": "Dérivé de schemas/openapi-genio.json ({n} chemins) plus la route WebSocket (hors OpenAPI par nature). Auth : header clé API ou Bearer courte durée si requis. Lecture seule — pas de console live.",
    "api.ws_note": "Flux d'ordres : envoyez {action:'prompt', text} → recevez stats/answer. Même modèle d'auth que HTTP.",
    "api.details": "Détails",
    "api.no_summary": "Voir le schéma OpenAPI",
    "api.auth_line": "Auth : selon l'endpoint (voir docs/API.md). Erreurs : HTTP standard + JSON nettoyé.",
    // docs.* (visionneuse docs — corps inchangés)
    "docs.page_title": "Docs",
    "docs.title": "Documentation",
    "docs.sub": "Sélectionnée depuis docs/ au build. Testée avec Genio 4.1.0.",
    "docs.search_label": "Rechercher dans la documentation",
    "docs.search_ph": "Rechercher…",
    "docs.source": "Source :",
    "docs.empty": "Aucune documentation trouvée.",
    "docs.crumb": "Docs",
    "docs.not_found": "Document introuvable.",
    "docs.tested_with": "Testé avec Genio 4.1.0 · source :",
    "auth.title": "Bienvenue sur Genio",
    "auth.subtitle": "Pour commencer, connectez-vous avec Google ou continuez sans compte.",
    "auth.why": "La connexion donne accès au cloud. Sans compte, Genio reste utilisable sur votre appareil.",
    "auth.google": "Se connecter avec Google",
    "auth.continue_google": "Continuer avec Google",
    "auth.continue": "Continuer",
    "auth.skip": "Continuer sans compte",
    "auth.signed_in": "Déjà connecté — touchez Continuer",
    "auth.agree": "En continuant vous acceptez l'utilisation de Genio. La clé reste sur votre appareil.",
    "auth.checking": "Vérification...",
    "shell.ready": "Genio est prêt",
    "shell.greeting": "Salut ! C'est Genio",
    "shell.listening": "Genio vous écoute",
    "shell.understanding": "Genio comprend votre demande",
    "shell.thinking": "Genio réfléchit",
    "shell.planning": "Genio planifie",
    "shell.explaining": "Genio répond",
    "shell.executing": "Genio travaille sur votre tâche",
    "shell.waiting": "Genio patiente",
    "shell.asking": "Genio attend votre réponse",
    "shell.success": "Tâche terminée",
    "shell.warning": "Attention, un point à voir",
    "shell.error": "Un problème est survenu",
    "shell.recovering": "Genio répare",
    "shell.celebrating": "Bravo, terminé !",
    "shell.sleeping": "Genio est en veille",
    "shell.disconnected": "Connexion perdue",
    "shell.attention": "Genio a besoin de vous",
    "shell.current_task": "Tâche actuelle",
    "shell.no_task": "Aucune tâche. Envoyez un message pour commencer.",
    "shell.resources": "Ressources",
    "shell.details": "Détails techniques",
    "shell.result": "Résultat",
    "shell.events": "Événements",
    "shell.cancel": "Annuler",
    "shell.reconnect": "Reconnecter",
    "shell.unavailable": "Indisponible",
    "shell.offline": "Hors ligne — navigation, docs, paramètres restent utilisables. L'IA nécessite une connexion.",
    "shell.connection_lost": "Connexion perdue",
    "shell.details_docs": "Détails dans les docs",
    "shell.advanced_on": "Avancé activé",
    "shell.opt_in": "Optionnel",
    "shell.hide_advanced": "Masquer avancé",
    "shell.show_advanced": "Afficher avancé",
    "input.placeholder": "Envoyer à Genio… (Entrée pour envoyer, Maj+Entrée pour un retour à la ligne)",
    "input.attach": "Joindre des fichiers",
    "input.mic": "Parler",
    "input.stop": "Arrêter l'enregistrement",
    "input.recording": "Enregistrement en cours...",
    "input.send": "Envoyer",
    "input.cancel": "Annuler",
    "input.drop": "Déposez les fichiers ici pour les joindre",
    "input.listening": "Genio vous écoute — parlez",
    "input.listen": "Écouter",
    "input.listen_label": "ÉCOUTER",
    "input.stop_recording": "Arrêter l'enregistrement",
    "input.live_transcription": "parlez… transcription en direct",
    "input.release_to_send": "relâchez pour envoyer via Web Audio",
    "input.send_label": "PRÊT",
    "errors.generic": "Erreur inattendue. Réessayez, puis envoyez les détails si ça persiste.",
    "errors.network": "Pas de connexion. Vérifiez Internet et réessayez.",
    "errors.auth": "Connexion requise pour continuer.",
    "errors.mic": "Microphone indisponible",
    "errors.server": "Le serveur ne répond pas. Réessayez dans un moment.",
    "errors.timeout": "Trop long sans réponse. Réessayez.",
    "errors.tech_details": "Détails techniques",
    "errors.cloud_auth": "Connectez-vous avec Google pour continuer dans le cloud",
    "errors.cloud_fail": "Problème de connexion au cloud — réessayez",
    "errors.cloud_retry": "Réessayer",
    "errors.google_signin": "Se connecter avec Google",
    "errors.mic_unavailable": "Microphone indisponible. Vérifiez les autorisations du navigateur.",
    "errors.google_auth_failed": "Connexion Google échouée. Réessayez.",
    "errors.recording": "Enregistrement",
    "errors.live_transcription": "Transcription en direct…",
    "errors.release_to_send": "Relâchez pour envoyer",
    "errors.close_chat": "Fermer le chat",
    "errors.open_chat": "Ouvrir le chat",
    "status.connected": "Connecté",
    "status.connecting": "Connexion...",
    "status.disconnected": "Déconnecté",
    "status.ready": "Prêt",
    "status.working": "En cours",
    "status.done": "Terminé",
    "task.title": "Tâche actuelle",
    "task.step": "Étape actuelle",
    "task.steps": "Étapes",
    "task.tool": "Outil",
    "task.duration": "Durée",
    "task.status": "État",
    "task.cancel": "Annuler la tâche",
    "task.cancel_requested": "Annulation demandée, en attente de confirmation...",
    "task.cancelled": "Tâche annulée",
    "task.queued": "En file",
    "task.running": "En cours",
    "task.waiting": "En attente",
    "task.completed": "Terminée",
    "task.failed": "Échouée",
    "task.elapsed": "Durée (mesurée sur votre appareil)",
    "settings.density": "Densité d'information",
    "settings.ambient": "Effets ambiants",
    "density.simple": "Simple",
    "density.detailed": "Détaillée",
    "density.advanced": "Avancée",
    "ambient.glow": "Lueur/particules",
    "ambient.reduced": "Mouvement réduit",
    "ambient.note": "Alertes, état des tâches et erreurs ne sont jamais désactivés par ces réglages.",
    "events.empty": "Aucun événement pour le moment.",
    "tool.activity": "Activité des outils",
    "tool.evidence_unavailable": "Aucune preuve disponible",
    "a11y.skip": "Aller au contenu",
    "a11y.nav_dialog": "Navigation",
    "a11y.open_menu": "Ouvrir le menu de navigation",
    "a11y.close": "Fermer",
    "a11y.menu": "Ouvrir le menu",
    "a11y.copy": "Copier la commande",
    "a11y.copied": "Copié ✓",
    "onboarding.welcome": "Bienvenue sur Genio",
    "onboarding.start": "Démarrer",
    "onboarding.skip": "Passer",
    // permissions.*
    "perm.checking": "Vérification des capacités de l'appareil...",
    "perm.title": "Autorisations et matériel",
    "perm.subtitle": "Genio a besoin de quelques autorisations pour fonctionner nativement sur Android",
    "perm.camera": "Caméra",
    "perm.camera_desc": "Suivi facial par caméra frontale (regard de l'avatar)",
    "perm.microphone": "Microphone",
    "perm.microphone_desc": "Saisie vocale native (STT Darija)",
    "perm.storage": "Stockage",
    "perm.storage_desc": "Pièces jointes et READ_MEDIA_*",
    "perm.network": "Réseau",
    "perm.network_desc": "INTERNET et ACCESS_NETWORK_STATE",
    "perm.grant_all": "Tout autoriser",
    "perm.reverify": "Revérifier",
    "perm.continue_anyway": "Continuer sans autorisations",
    "perm.continue": "Continuer",
    "perm.tauri_note": "Tauri Android impose aussi les permissions du manifest : CAMERA, RECORD_AUDIO, INTERNET, ACCESS_NETWORK_STATE, READ_MEDIA_*.",
    "perm.skip": "Passer l'onboarding",
    // header.*
    "header.toggle_drawer": "Ouvrir le tiroir",
    "header.selfie_mode": "MODE SELFIE",
    "header.toggle_selfie": "Basculer le suivi facial",
    "header.stop": "Arrêter",
    "header.disconnect": "Déconnecter",
    "header.thinking": "Réflexion...",
    "header.executing": "Exécution : ",
    "header.completed": "Terminé",
    "header.stale": "Périmé",
    "header.telemetry_paused": "Télémétrie en pause — serveur occupé",
    // mascot.*
    "mascot.listening": "écoute...",
    "mascot.speaking": "parle...",
    "mascot.tap_to_speak": "Touchez pour parler",
    "mascot.gesture_note": "gestes appris pour cet utilisateur",
    "mascot.technical_mode": "Mode technique",
    "mascot.mic_start": "Parler à Genio",
    "mascot.mic_stop": "Arrêter le micro",
    // telemetry.*
    "telemetry.offline": "🔴 Hors ligne",
    "telemetry.thinking": "🟡 Genio réfléchit...",
    "telemetry.streaming": "🔵 Répond",
    "telemetry.ready": "🟢 Connecté",
    // app.* (App shell mode buttons + background actions)
    "app.mode_technique": "Mode technique",
    "app.mode_mascot": "Mode mascotte",
    "app.mode_unified": "Mode unifié",
    "app.mode_mascot_title": "Retour à la mascotte plein écran",
    "app.mode_unified_title": "Vue unifiée : conversation, présence et tâche",
    "app.kill_agent": "Arrêter l'agent",
    "app.disconnect": "Déconnecter",
    // error boundary fallback
    "boundary.crash": "La scène a planté — mode de secours actif.",
    "boundary.mascot_crash_hint": "La 3D n'a pas démarré sur cet appareil — continuez en mode technique ou unifié, discussion et connexion préservées.",
    // permission status values (device messages mapped, never raw English)
    "perm.status_granted": "Autorisé",
    "perm.status_online": "En ligne",
    "perm.status_offline": "Hors ligne",
    "perm.status_denied": "Refusé — voir réglages système",
    "perm.status_denied_retry": "Refusé — redemandable",
    "perm.status_unavailable": "Indisponible sur cet appareil",
    // chat panel (FAB)
    "chat.title": "Discussion Genio",
    "chat.empty": "✨ Genio écoute — écrivez ou parlez ✨",
  },
  en: {
    nav_home: "Genio",
    nav_explore: "Explore", nav_security: "Security", nav_docs: "Docs",
    nav_download: "Download", nav_install: "Install Genio now", nav_app: "App",
    install_title: "Install Genio now", try: "Try Genio", docs: "Docs",
    offline: "No Internet connection", error: "Something went wrong",
    retry: "Retry", task: "Task", evidence: "Evidence",
    settings: "Settings", assistant: "Assistant", start: "Start",
    tools_activity: "Tool activity",
    // footer.* (public portal footer)
    "footer.docs": "Docs",
    "footer.security": "Security",
    "footer.api": "API",
    "footer.tag": "sovereign • HiTechLab 🇹🇳",
    // landing.* (landing page — Tunisian-first, EN secondary)
    "landing.brand_tag": "Genio",
    "landing.live": "SYSTEM LIVE",
    "landing.founder": "Founder",
    "landing.enter_app": "Open the app",
    "landing.hero_badge": "First Tunisian AI companion — in Darija",
    "landing.hero_title_a": "First Tunisian",
    "landing.hero_title_b": "AI companion",
    "landing.hero_title_c": "",
    "landing.hero_sub": "Genio understands your Darija, organizes your work, codes, monitors your servers and controls your smart home — from your phone or PC. Privacy guaranteed, local or cloud, your choice.",
    "landing.cta_try": "Try Genio now →",
    "landing.cta_install": "Install Genio ↓",
    "landing.cta_how": "How does it work?",
    "landing.product_explore": "Explore",
    "landing.product_download": "Download",
    "landing.product_install": "Install",
    "landing.product_docs": "Docs",
    "landing.product_security": "Security",
    "landing.no_key_note": "No API key in the browser • offline Tier A • voice and vision",
    "landing.how_title": "How it works — 3 steps",
    "landing.how_1t": "Speak Darija",
    "landing.how_1d": "Type or speak: organize my server, turn on the light — Genio understands Arabic, Darija, French and English.",
    "landing.how_2t": "Genio plans and executes",
    "landing.how_2d": "It analyzes your request, uses tools (bash, browser, files) and shows every step in Matrix.",
    "landing.how_3t": "See the result",
    "landing.how_3d": "Voice and visual answers, with files and tables. If you want, it keeps working in the background.",
    "landing.tech_title": "Technology and privacy",
    "landing.tech_1t": "Secure cloud",
    "landing.tech_1d": "Gemini 2.0 Flash through an encrypted server-side gateway — the key never leaves the server, no API key in the browser or APK.",
    "landing.tech_2t": "Also works locally",
    "landing.tech_2d": "If the server is down, Genio continues on-device (Tier A) — no interruption.",
    "landing.tech_3t": "Voice and vision",
    "landing.tech_3d": "Darija (ar-TN) voice recognition with face tracking. Your privacy is protected: microphone and camera only with your permission.",
    "landing.tech_4t": "Open, extensible code",
    "landing.tech_4d": "New tools, scripts, even voices — everything customizable.",
    "landing.road_title": "Roadmap — 4 phases",
    "landing.road_1p": "Phase 1",
    "landing.road_1t": "Academy — ghost courses + Genio tutor",
    "landing.road_1d": "Recorded courses + Genio explains, quizzes and corrects — like a private tutor 24/7.",
    "landing.road_2p": "Phase 2",
    "landing.road_2t": "Education Edition — explain and revise in Darija",
    "landing.road_2d": "Primary, secondary and university in Tunisian Darija — summaries, exercises, smart revision.",
    "landing.road_3p": "Phase 3",
    "landing.road_3t": "SysAdmin — Docker + VPN + automation scripts",
    "landing.road_3d": "Servers, containers, networks and VPN in one click — Genio writes and runs the scripts.",
    "landing.road_4p": "Phase 4",
    "landing.road_4t": "Daily Automation — n8n + smart devices + mobile voice",
    "landing.road_4d": "Daily automation: n8n, smart home, voice commands on the road.",
    "landing.founder_title": "Founder — Mohamed Azmi Kaanich",
    "landing.founder_body": "Infrastructure and automation expert — years in Docker, networks and VPN. His goal is breaking the barrier between Tunisians and technology: Genio is built so every Tunisian — student, artisan, engineer — can use AI in their language, with trust, their way.",
    "landing.founder_more": "Read more →",
    "landing.platform_title": "Where can you use Genio?",
    "landing.platform_linux": "Linux (AppImage / DEB)",
    "landing.platform_linux_ok": "✅ Available — v5.0.0",
    "landing.platform_docker": "Docker",
    "landing.platform_docker_ok": "✅ Available",
    "landing.platform_other": "Windows / macOS / Android / iOS",
    "landing.platform_other_no": "❌ Not available yet",
    "landing.platform_os": "HiTech-OS",
    "landing.platform_os_soon": "Contract ready — implementation later",
    "landing.platform_all": "All download options ←",
    "landing.install_title": "Install Genio in 3 steps",
    "landing.install_1t": "Download",
    "landing.install_1d": "The archive + checksum from the v5.0.0 page",
    "landing.install_2t": "Install",
    "landing.install_2d": "Via CLI or AppImage — doctor verifies",
    "landing.install_3t": "Verify",
    "landing.install_3d": "genio doctor → HEALTHY (0 FAIL)",
    "landing.install_more": "Install assistant ←",
    "landing.footer_made": "Genio — made in Tunisia 🇹🇳 with love",
    "landing.footer_rights": "your privacy first",
    "landing.footer_enter": "Enter",
    "landing.footer_about": "About us",
    "landing.alt_hero": "Genio Hero — red Jebba",
    "landing.alt_founder": "Mohamed Azmi Kaanich",
    // install.* (install assistant — commands stay exact, prose localized)
    "install.page_title": "Install",
    "install.title": "Install Genio",
    "install.sub": "Preview / documentation mode: this page guides a real installation — it does not install anything itself. Every state below mirrors the real installer state machine.",
    "install.platform_card": "Detected platform",
    "install.platform_line": "Detected platform (client-side only, nothing transmitted):",
    "install.cmd_install": "install command",
    "install.cmd_docker": "docker command",
    "install.understood": "UNDERSTOOD",
    "install.pending": "PENDING",
    "install.mark_pending": "Mark as pending",
    "install.mark_understood": "Mark as understood",
    "install.reset": "reset",
    "install.gotit": "got it",
    "install.viz_title": "Visualize a real installer log (paste --json-events output)",
    "install.viz_help": "Run genio install --json-events … in your terminal, paste the output below. States render deterministically from real events — invalid lines are flagged, never hidden.",
    "install.viz_log_label": "Installer event log",
    "install.viz_render": "Render timeline",
    "install.viz_empty": "Empty log — nothing rendered (honest).",
    "install.viz_invalid": "INVALID LINE:",
    "install.viz_recovery": "Recovery:",
    "install.viz_docs": "Docs →",
    "install.viz_timeline": "Installer event timeline",
    "install.help_title": "Verify, recover, get help (real commands)",
    "install.code_verify": "verify",
    "install.code_repair": "repair",
    "install.code_rollback": "rollback",
    "install.go_download": "Download center",
    "install.go_docs": "Installation docs",
    "install.state_detecting_label": "Detecting system",
    "install.state_detecting_desc": "Probing OS, hardware, tools, ports and existing installations.",
    "install.state_checking_label": "Preflight checks",
    "install.state_checking_desc": "Validating requirements before any change.",
    "install.state_ready_label": "Ready",
    "install.state_ready_desc": "System ready; awaiting user confirmation.",
    "install.state_downloading_label": "Downloading",
    "install.state_downloading_desc": "Fetching the release artifact. Real bytes only.",
    "install.state_verifying_label": "Verifying integrity",
    "install.state_verifying_desc": "SHA-256 (and signature when available) checked. Mismatch aborts.",
    "install.state_installing_label": "Installing",
    "install.state_installing_desc": "Extracting, creating venv, installing pinned dependencies.",
    "install.state_configuring_label": "Configuring",
    "install.state_configuring_desc": "Writing config, ports and environment (never secrets in logs).",
    "install.state_securing_label": "Securing",
    "install.state_securing_desc": "File permissions, boot-guard check, cloud default closed.",
    "install.state_health_check_label": "Health check",
    "install.state_health_check_desc": "Import verify, API probe, sandbox probe. Process alive is not enough.",
    "install.state_complete_label": "Ready",
    "install.state_complete_desc": "Installation verified healthy.",
    // download.* (download center — commands/URLs stay exact)
    "download.page_title": "Download",
    "download.title": "Download Genio",
    "download.sub": "Version {v}. Detected platform: {p} (manual choice always allowed).",
    "download.available": "AVAILABLE",
    "download.unavailable": "NOT AVAILABLE",
    "download.cmd": "install command",
    "download.why_unavailable": "Build currently unavailable — {r}. No fake download button is shown.",
    "download.release": "Release {t}",
    "download.manifest": "Release manifest",
    "download.sbom": "SBOM",
    // security.* (security center — proofs stay exact identifiers)
    "security.page_title": "Security",
    "security.title": "Security Center",
    "security.sub": "Every claim links to a test, audit or implementation. Nothing here means “100% secure”.",
    "security.details": "Details & proof",
    "security.proof": "Proof:",
    "security.tag_verified": "IMPLEMENTED + VERIFIED",
    "security.tag_conditional": "CONDITIONAL",
    "security.tag_pending": "PENDING",
    "security.tag_pending_gated": "PENDING — gated in 5.0",
    "security.sandbox.title": "Fail-closed sandbox",
    "security.sandbox.body": "Strict mode without Docker refuses host execution (rc 125, SANDBOX_UNAVAILABLE). Proven live in dev, prefix installs and containers.",
    "security.policy.title": "Policy engine",
    "security.policy.body": "Every action passes a central ALLOW/DENY/ESCALATE gate. Destructive ops need confirmation.",
    "security.filesystem.title": "Filesystem boundary",
    "security.filesystem.body": "Authorization happens after realpath canonicalization (symlinks, .., /etc, devices blocked).",
    "security.bash.title": "Structured Bash",
    "security.bash.body": "20 command classes validated structurally (injection, substitution, interpreters, fork bombs).",
    "security.ssrf.title": "Browser anti-SSRF",
    "security.ssrf.body": "Private IPs, localhost, metadata endpoints and DNS-rebinding blocked fail-closed.",
    "security.upload.title": "Upload validation",
    "security.upload.body": "Magic bytes (never client MIME), 50MB quota, 1h TTL, 0o600 storage.",
    "security.auth.title": "API authentication",
    "security.auth.body": "Short-lived Bearer (15min HMAC), rate limits, strict/prod refuses keyless boot.",
    "security.killswitch.title": "Kill switch",
    "security.killswitch.body": "Preemptive halt incl. child processes; re-arm always explicit.",
    "security.telemetry.title": "Telemetry scrubbing",
    "security.telemetry.body": "Keys, tokens, cookies and secrets scrubbed; telemetry stays useful.",
    "security.ipc.title": "IPC security",
    "security.ipc.body": "Same-UID auth (localhost is not trusted), nonce anti-replay, rate limit, full audit.",
    "security.container.title": "Container hardening",
    "security.container.body": "Non-root user, HEALTHCHECK, pinned deps, no secrets in layers.",
    "security.release.title": "Release integrity",
    "security.release.body": "Versioned archives + SHA-256 + manifests verified fail-closed (tamper-tested).",
    "security.cloud.title": "Cloud routing",
    "security.cloud.body": "Cloud backends stay disabled unless GENIO_ALLOW_CLOUD is explicitly set.",
    "security.voice.title": "Voice service",
    "security.voice.body": "External VODER; honest 422/400 errors, no silent 500, no orphans.",
    "security.admin.title": "Admin page",
    "security.admin.body": "/genio/admin currently has no auth gate. It must require a user-provided API key verified against the backend before showing internal stats.",
    "security.edge.title": "Production edge",
    "security.edge.body": "Public traffic currently terminates at dev servers (vite preview + direct uvicorn). CSP/headers audit scheduled.",
    // explore.* (architecture explorer — identifiers/paths stay exact)
    "explore.page_title": "Explore",
    "explore.title": "How Genio works",
    "explore.sub": "Click any area for purpose, boundary and honest status. Blocked areas never look ready.",
    "explore.purpose": "Purpose & boundary",
    "explore.what": "What:",
    "explore.boundary": "Boundary:",
    "explore.docs": "Documentation ←",
    "explore.go_security": "Security Center",
    "explore.go_api": "API Explorer",
    "explore.status_production": "PRODUCTION",
    "explore.status_conditional": "CONDITIONAL",
    "explore.status_desktop": "BLOCKED — no Rust toolchain here",
    "explore.status_mobile": "BLOCKED — signing external",
    "explore.status_hitechos": "CONTRACT READY / IMPL PENDING",
    "explore.agent.what": "Multi-step task execution (≤5 iterations, budgets enforced).",
    "explore.agent.boundary": "Every step passes policy; tools are allow-listed.",
    "explore.policy.what": "Central ALLOW / DENY / ESCALATE gate for every action.",
    "explore.policy.boundary": "Policy lives in Genio; OS and UI can only request.",
    "explore.router.what": "local → Ollama → HiTech-OS → cloud (explicit opt-in).",
    "explore.router.boundary": "Cloud closed by default; no silent data transfer.",
    "explore.memory.what": "Session recall with audit metadata and poisoning guards.",
    "explore.memory.boundary": "Per-session isolation; provenance tracked.",
    "explore.tools.what": "Bash (structured), filesystem (bounded), browser, computer-use.",
    "explore.tools.boundary": "Each tool has capability + policy + audit.",
    "explore.sandbox.what": "Docker containers, quotas, read-only FS. Fail-closed.",
    "explore.sandbox.boundary": "Sandbox failure = no host execution, always.",
    "explore.ipc.what": "UDS contract: hello/capabilities/infer, errors, events.",
    "explore.ipc.boundary": "Same-UID auth, nonce, rate-limit, audit.",
    "explore.installer.what": "Manifests, backups, repair/update/rollback, doctor.",
    "explore.installer.boundary": "Never deletes user data silently; confirmations required.",
    "explore.docker.what": "Hardened image: non-root, HEALTHCHECK, pinned deps.",
    "explore.docker.boundary": "No secrets in layers; socket only when sandbox needed.",
    "explore.models.what": "Local Ollama (gemma4:12b resident); honest UNAVAILABLE states.",
    "explore.models.boundary": "VRAM contention declared; no fake readiness.",
    "explore.voice.what": "STT + VODER TTS (auto language; explicit 422 otherwise).",
    "explore.voice.boundary": "External service; degrades honestly.",
    "explore.desktop.what": "Native client via HTTP API + WS (contract validated).",
    "explore.desktop.boundary": "No secrets embedded; no privileged IPC from UI.",
    "explore.mobile.what": "Same API contract; secure storage, TLS, degraded mode.",
    "explore.mobile.boundary": "APK signing requires release secrets.",
    "explore.hitechos.what": "OS consumes Genio over IPC; both stay independent.",
    "explore.hitechos.boundary": "Contract only; daemon IPC implementation pending OS-side.",
    // api.* (API explorer — paths/summaries stay technical, chrome localized)
    "api.page_title": "API",
    "api.title": "API Explorer",
    "api.sub": "Derived from schemas/openapi-genio.json ({n} paths) plus the WebSocket route (not part of OpenAPI by nature). Authentication: API key header or short-lived Bearer where required. This explorer is read-only — no live console.",
    "api.ws_note": "Prompt stream: send {action:'prompt', text} → receive stats/answer frames. Same auth model as HTTP.",
    "api.details": "Details",
    "api.no_summary": "See OpenAPI schema",
    "api.auth_line": "Auth: endpoint-dependent (see docs/API.md). Errors: standard HTTP + sanitized JSON.",
    // docs.* (docs viewer chrome — doc bodies stay as authored)
    "docs.page_title": "Docs",
    "docs.title": "Documentation",
    "docs.sub": "Curated from docs/ at build time. Tested with Genio 4.1.0.",
    "docs.search_label": "Search documentation",
    "docs.search_ph": "Search docs…",
    "docs.source": "source:",
    "docs.empty": "No documentation matches.",
    "docs.crumb": "Docs",
    "docs.not_found": "Document not found.",
    "docs.tested_with": "tested with Genio 4.1.0 · source:",
    "auth.title": "Welcome to Genio",
    "auth.subtitle": "To get started, sign in with Google or continue without an account.",
    "auth.why": "Signing in unlocks the cloud. Without an account Genio still works on your device.",
    "auth.google": "Sign in with Google",
    "auth.continue_google": "Continue with Google",
    "auth.continue": "Continue",
    "auth.skip": "Continue without an account",
    "auth.signed_in": "Already signed in — tap Continue",
    "auth.agree": "By continuing you accept using Genio. The key stays on your device.",
    "auth.checking": "Checking...",
    "shell.ready": "Genio is ready",
    "shell.greeting": "Hi! I am Genio",
    "shell.listening": "Genio is listening",
    "shell.understanding": "Genio is understanding your request",
    "shell.thinking": "Genio is thinking",
    "shell.planning": "Genio is planning",
    "shell.explaining": "Genio is answering",
    "shell.executing": "Genio is working on your task",
    "shell.waiting": "Genio is waiting",
    "shell.asking": "Genio is waiting for your reply",
    "shell.success": "Task completed",
    "shell.warning": "Attention needed",
    "shell.error": "Something went wrong",
    "shell.recovering": "Genio is recovering",
    "shell.celebrating": "Well done, completed!",
    "shell.sleeping": "Genio is asleep",
    "shell.disconnected": "Connection lost",
    "shell.attention": "Genio needs your attention",
    "shell.current_task": "Current task",
    "shell.no_task": "No task yet. Send a message to start.",
    "shell.resources": "Resources",
    "shell.details": "Technical details",
    "shell.result": "Result",
    "shell.events": "Events",
    "shell.cancel": "Cancel",
    "shell.reconnect": "Reconnect",
    "shell.unavailable": "Unavailable",
    "shell.offline": "Offline — navigation, docs, settings and preferences stay usable. AI features need a connection.",
    "shell.connection_lost": "Connection lost",
    "shell.details_docs": "Details in docs",
    "shell.advanced_on": "advanced on",
    "shell.opt_in": "opt-in",
    "shell.hide_advanced": "Hide advanced",
    "shell.show_advanced": "Show advanced",
    "input.placeholder": "Message Genio… (Enter to send, Shift+Enter for newline)",
    "input.attach": "Attach files",
    "input.mic": "Speak",
    "input.stop": "Stop recording",
    "input.recording": "Recording",
    "input.send": "Send",
    "input.cancel": "Cancel",
    "input.drop": "Drop files here to attach",
    "input.listening": "Genio is listening — speak now",
    "input.listen": "Listen",
    "input.listen_label": "LISTEN",
    "input.stop_recording": "Stop recording",
    "input.live_transcription": "live transcription: speak…",
    "input.release_to_send": "release to send via Web Audio",
    "input.send_label": "READY",
    "errors.generic": "Unexpected error. Try again, and send details if it persists.",
    "errors.network": "No connection. Check the Internet and retry.",
    "errors.auth": "Sign-in required to continue.",
    "errors.mic": "Microphone unavailable",
    "errors.server": "The server did not answer. Retry in a moment.",
    "errors.timeout": "Took too long. Retry.",
    "errors.tech_details": "Technical details",
    "errors.cloud_auth": "Sign in with Google to continue in the cloud",
    "errors.cloud_fail": "Cloud connection problem — retry",
    "errors.cloud_retry": "Retry",
    "errors.google_signin": "Sign in with Google",
    "errors.mic_unavailable": "Microphone unavailable. Check browser permission.",
    "errors.google_auth_failed": "Google sign-in failed. Try again.",
    "errors.recording": "Recording",
    "errors.live_transcription": "Live transcription…",
    "errors.release_to_send": "Release to send",
    "errors.close_chat": "Close chat",
    "errors.open_chat": "Open chat",
    "status.connected": "Connected",
    "status.connecting": "Connecting...",
    "status.disconnected": "Disconnected",
    "status.ready": "Ready",
    "status.working": "Working",
    "status.done": "Done",
    "task.title": "Current task",
    "task.step": "Current step",
    "task.steps": "Steps",
    "task.tool": "Tool",
    "task.duration": "Duration",
    "task.status": "Status",
    "task.cancel": "Cancel task",
    "task.cancel_requested": "Cancellation requested, waiting for confirmation...",
    "task.cancelled": "Task cancelled",
    "task.queued": "Queued",
    "task.running": "Running",
    "task.waiting": "Waiting",
    "task.completed": "Completed",
    "task.failed": "Failed",
    "task.elapsed": "Elapsed (measured on your device)",
    "settings.density": "Information density",
    "settings.ambient": "Ambient effects",
    "density.simple": "Simple",
    "density.detailed": "Detailed",
    "density.advanced": "Advanced",
    "ambient.glow": "Glow/particles",
    "ambient.reduced": "Reduced motion",
    "ambient.note": "Security alerts, task state and errors are never disabled by these settings.",
    "events.empty": "No events yet.",
    "tool.activity": "Tool activity",
    "tool.evidence_unavailable": "No evidence available",
    "a11y.skip": "Skip to content",
    "a11y.nav_dialog": "Navigation",
    "a11y.open_menu": "Open navigation menu",
    "a11y.close": "Close",
    "a11y.menu": "Open menu",
    "a11y.copy": "Copy command",
    "a11y.copied": "Copied ✓",
    "onboarding.welcome": "Welcome to Genio",
    "onboarding.start": "Start",
    "onboarding.skip": "Skip",
    // permissions.*
    "perm.checking": "Checking device capabilities...",
    "perm.title": "Permissions & Hardware",
    "perm.subtitle": "Genio needs a few capabilities to run natively on Android",
    "perm.camera": "Camera",
    "perm.camera_desc": "Front-camera face tracking (Chachia avatar gaze)",
    "perm.microphone": "Microphone",
    "perm.microphone_desc": "Native voice input (Darija STT)",
    "perm.storage": "Storage",
    "perm.storage_desc": "Attachments & READ_MEDIA_*",
    "perm.network": "Network",
    "perm.network_desc": "INTERNET & ACCESS_NETWORK_STATE",
    "perm.grant_all": "Grant all",
    "perm.reverify": "Re-verify",
    "perm.continue_anyway": "Continue anyway",
    "perm.continue": "Continue",
    "perm.tauri_note": "Tauri Android will also enforce manifest permissions: CAMERA, RECORD_AUDIO, INTERNET, ACCESS_NETWORK_STATE, READ_MEDIA_*.",
    "perm.skip": "skip onboarding",
    // header.*
    "header.toggle_drawer": "Toggle drawer",
    "header.selfie_mode": "SELFIE MODE",
    "header.toggle_selfie": "Toggle selfie face tracking",
    "header.stop": "Stop",
    "header.disconnect": "Disconnect",
    "header.thinking": "Thinking...",
    "header.executing": "Exec: ",
    "header.completed": "Completed",
    "header.stale": "Stale",
    "header.telemetry_paused": "Telemetry paused — backend event loop busy",
    // mascot.*
    "mascot.listening": "listening...",
    "mascot.speaking": "speaking...",
    "mascot.tap_to_speak": "Tap to speak",
    "mascot.gesture_note": "gestures learned for this user",
    "mascot.technical_mode": "Technical mode",
    "mascot.mic_start": "Talk to Genio",
    "mascot.mic_stop": "Stop the mic",
    // telemetry.*
    "telemetry.offline": "🔴 Offline",
    "telemetry.thinking": "🟡 Genio thinking...",
    "telemetry.streaming": "🔵 Streaming",
    "telemetry.ready": "🟢 Ready",
    // app.* (App shell mode buttons + background actions)
    "app.mode_technique": "Technical mode",
    "app.mode_mascot": "Mascot mode",
    "app.mode_unified": "Unified mode",
    "app.mode_mascot_title": "Back to fullscreen mascot",
    "app.mode_unified_title": "Unified view: conversation, presence and task",
    "app.kill_agent": "Kill agent",
    "app.disconnect": "Disconnect",
    // error boundary fallback
    "boundary.crash": "Scene crashed — fallback active.",
    "boundary.mascot_crash_hint": "3D did not start on this device — continue in technical or unified mode; chat and connection are preserved.",
    // permission status values (device messages mapped, never raw English)
    "perm.status_granted": "Granted",
    "perm.status_online": "Online",
    "perm.status_offline": "Offline",
    "perm.status_denied": "Denied — check OS settings",
    "perm.status_denied_retry": "Denied — can request again",
    "perm.status_unavailable": "Unavailable on this device",
    // chat panel (FAB)
    "chat.title": "Genio Chat",
    "chat.empty": "✨ Genio is listening — type or speak ✨",
  },
};

const KEY = "genio-lang";

export function getLang(): Lang {
  try {
    const v = localStorage.getItem(KEY);
    if (v === "fr" || v === "en" || v === "tu") return v;
  } catch { /* ignore */ }
  return "tu";
}

export function setLang(lang: Lang): void {
  try {
    localStorage.setItem(KEY, lang);
  } catch { /* ignore */ }
  if (typeof document !== "undefined") {
    document.documentElement.lang = lang === "tu" ? "ar" : lang;
    document.documentElement.dir = lang === "tu" ? "rtl" : "ltr";
  }
  // Notify same-tab subscribers (useLang hook). Without this, only the
  // component that called setLang re-renders and page bodies keep the old
  // language while the nav already switched. Storage events only fire
  // across tabs, so an explicit in-page event is required here.
  try {
    if (typeof window !== "undefined") window.dispatchEvent(new Event("genio:lang"));
  } catch { /* ignore */ }
}

export function t(lang: Lang, key: string): string {
  return STRINGS[lang][key] ?? STRINGS.tu[key] ?? key;
}

/** Template translation: replaces {name} placeholders with vars. */
export function tt(lang: Lang, key: string, vars: Record<string, string>): string {
  let s = t(lang, key);
  for (const [k, v] of Object.entries(vars)) s = s.split(`{${k}}`).join(v);
  return s;
}

export function applyStoredLang(): void {
  const lang = getLang();
  if (typeof document !== "undefined") {
    document.documentElement.lang = lang === "tu" ? "ar" : lang;
    document.documentElement.dir = lang === "tu" ? "rtl" : "ltr";
  }
}

/** Reactive language hook: re-renders on language switch (same-tab + other tabs). */
export function useLang(): [Lang, (l: Lang) => void] {
  const [lang, setLangState] = useState<Lang>(() => getLang());
  useEffect(() => {
    const sync = () => {
      const next = getLang();
      setLangState((prev) => (prev === next ? prev : next));
    };
    window.addEventListener("storage", sync);
    window.addEventListener("genio:lang", sync);
    return () => {
      window.removeEventListener("storage", sync);
      window.removeEventListener("genio:lang", sync);
    };
  }, []);
  const change = (l: Lang) => {
    setLang(l);
    setLangState(l);
    window.dispatchEvent(new Event("genio:lang"));
  };
  return [lang, change];
}

/**
 * Map internal error strings to friendly localized user-facing messages.
 * Internal/technical details are hidden behind `errors.tech_details`.
 * Never expose secrets, tokens, paths, or stack traces.
 */
export function mapError(lang: Lang, raw: string): { friendly: string; technical?: string } {
  const s = (raw || "").toLowerCase();
  if (s.includes("no_google_token") || s.includes("need_google_auth")) {
    return { friendly: t(lang, "errors.cloud_auth") };
  }
  if (s.includes("gemini_proxy_fail") || s.includes("السيرفر طايح") || s.includes("server")) {
    return { friendly: t(lang, "errors.cloud_fail"), technical: raw };
  }
  if (s.includes("microphone") || s.includes("mic") || s.includes("permission")) {
    return { friendly: t(lang, "errors.mic_unavailable") };
  }
  if (s.includes("network") || s.includes("fetch") || s.includes("offline")) {
    return { friendly: t(lang, "errors.network") };
  }
  if (s.includes("timeout")) {
    return { friendly: t(lang, "errors.timeout") };
  }
  if (s.includes("google") && (s.includes("sign") || s.includes("auth") || s.includes("login"))) {
    return { friendly: t(lang, "errors.google_auth_failed") };
  }
  // Generic fallback — never leak raw internals
  return { friendly: t(lang, "errors.generic"), technical: raw };
}

/**
 * Map raw device permission status messages (English, from browser/OS APIs)
 * to friendly localized labels. Raw strings are never shown to the user.
 */
export function mapPermStatus(lang: Lang, granted: boolean, message: string): string {
  const s = (message || "").toLowerCase();
  if (s.includes("online")) return t(lang, "perm.status_online");
  if (s.includes("offline")) return t(lang, "perm.status_offline");
  if (granted) return t(lang, "perm.status_granted");
  if (s.includes("denied") && (s.includes("os settings") || s.includes("système") || s.includes("system"))) {
    return t(lang, "perm.status_denied");
  }
  if (s.includes("denied") || s.includes("notallowed") || s.includes("permission")) {
    return t(lang, "perm.status_denied_retry");
  }
  return t(lang, "perm.status_unavailable");
}
