"""Standalone prefix installation (fresh install path)."""
import json
import shutil

from installer.core.errors import InstallerError, EXIT_INSTALL_FAIL, EXIT_VERIFY_FAIL
from installer.core.manifest import new_manifest, record_event, write_manifest
from installer.core.paths import layout


def _copy_source(runner, source, dest):
    """Obtain code: git clone (URL or local path) or plain copy."""
    from pathlib import Path
    src = str(source)
    if (Path(src) / ".git").is_dir() or src.startswith(("http://", "https://", "git@")):
        r = runner.run(["git", "clone", src, str(dest)], timeout=600)
        if not r["ok"]:
            raise InstallerError(f"git clone failed: {r['err'][-400:]}",
                                 EXIT_INSTALL_FAIL, hint="check URL/network")
        return "git"
    if Path(src).is_dir():
        shutil.copytree(src, dest, ignore=shutil.ignore_patterns(
            ".git", "__pycache__", "*.pyc", "node_modules", ".venv", "venv*",
            "*.db", "*.db-journal", "dist", ".pytest_cache"))
        return "copy"
    raise InstallerError(f"source not usable: {src}", EXIT_INSTALL_FAIL)


def _head_commit(repo):
    from installer.core.runner import Runner
    r = Runner().run(["git", "-C", str(repo), "rev-parse", "--short", "HEAD"], timeout=20)
    return r["out"].strip()[:12] if r["ok"] else "unknown"


def _make_venv(runner, venv_path, log):
    r = runner.run(["python3", "-m", "venv", str(venv_path)], timeout=300)
    if not r["ok"]:
        raise InstallerError(f"venv creation failed: {r['err'][-400:]}", EXIT_INSTALL_FAIL)
    pip = venv_path / "bin" / "pip"
    r = runner.run([str(pip), "install", "--upgrade", "pip"], timeout=300)
    if not r["ok"]:
        raise InstallerError("pip upgrade failed", EXIT_INSTALL_FAIL)


def _install_deps(runner, venv_path, repo):
    pip = venv_path / "bin" / "pip"
    req = repo / "requirements.txt"
    if not req.is_file():
        raise InstallerError("requirements.txt missing from source", EXIT_INSTALL_FAIL)
    r = runner.run([str(pip), "install", "-r", str(req)], timeout=1800)
    if not r["ok"]:
        raise InstallerError(f"pip install failed: {r['err'][-500:]}",
                             EXIT_INSTALL_FAIL,
                             hint="see log; missing system libs (libsndfile1?)")
    return True


def _build_frontend(runner, repo, npm_ok):
    client = repo / "genio_client"
    if not (client / "package.json").is_file():
        return {"status": "NOT_APPLICABLE", "detail": "no frontend in source"}
    if not npm_ok:
        return {"status": "NOT_APPLICABLE",
                "detail": "npm absent — frontend skipped honestly, API unaffected"}
    r = runner.run(["npm", "ci", "--no-audit", "--no-fund"], cwd=client, timeout=1200)
    if not r["ok"]:
        return {"status": "FAIL", "detail": f"npm ci failed: {r['err'][-300:]}"}
    r = runner.run(["npm", "run", "build"], cwd=client, timeout=1200)
    if not r["ok"] or not (client / "dist" / "index.html").is_file():
        return {"status": "FAIL", "detail": "frontend build produced no dist/index.html"}
    return {"status": "PASS", "detail": "dist/index.html built"}


def _write_env(env_file, api_key, extra):
    env_file.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by genio installer — edit carefully.",
        "GENIO_ENV=dev",
        "GENIO_SECURITY_MODE=development",
        "GENIO_SANDBOX_MODE=local",
        "GENIO_ALLOW_CLOUD=",
    ]
    if api_key:
        lines.append(f"GENIO_API_KEY={api_key}")
    for k, v in (extra or {}).items():
        lines.append(f"{k}={v}")
    env_file.write_text("\n".join(lines) + "\n")
    try:
        import os
        os.chmod(env_file, 0o600)
    except OSError:
        pass


def install(runner, prefix, source, version, opts):
    """Fresh prefix install. Returns manifest. Raises InstallerError."""
    lay = layout(prefix)
    for d in ("meta", "repo", "config", "data", "cache", "logs", "tmp"):
        lay[d].mkdir(parents=True, exist_ok=True)
    mode = _copy_source(runner, source, lay["repo"])
    commit = _head_commit(lay["repo"]) if mode == "git" else "copy"
    _make_venv(runner, lay["venv"], runner.log_path)
    _install_deps(runner, lay["venv"], lay["repo"])
    fe = _build_frontend(runner, lay["repo"], opts.get("npm_ok", False))
    ports = dict(opts.get("ports") or {})
    lay["ports_file"].write_text(json.dumps(ports, indent=2, sort_keys=True))
    _write_env(lay["env_file"], opts.get("api_key", ""), opts.get("env_extra"))
    man = new_manifest(lay["prefix"], version, commit,
                       "standalone" if mode == "git" else "standalone-copy")
    man["ports"] = ports
    record_event(man, "install", f"source={mode} frontend={fe['status']}")
    write_manifest(lay["manifest"], man)
    # Post-install verify: python can import the product from the prefix.
    py = lay["venv"] / "bin" / "python"
    r = runner.run([str(py), "-c",
                    "import sys; sys.path.insert(0, '.');"
                    "import config; print(config.get_config().ollama.primary_model)"],
                   cwd=lay["repo"], timeout=120)
    if not r["ok"]:
        raise InstallerError(f"post-install import verify failed: {r['err'][-400:]}",
                             EXIT_VERIFY_FAIL)
    man["health"] = "healthy"
    record_event(man, "verify", "import check passed")
    write_manifest(lay["manifest"], man)
    man["_frontend"] = fe
    return man
