"""Standalone prefix installation (fresh install path)."""
import json
import shutil

from installer.core.errors import InstallerError, EXIT_INSTALL_FAIL, EXIT_VERIFY_FAIL
from installer.core.manifest import new_manifest, record_event, write_manifest
from installer.core.paths import layout


def _copy_source(runner, source, dest, checksum=None):
    """Obtain code: git clone, release archive (.tar.gz + sha256), or copy."""
    from pathlib import Path
    src = str(source)
    if src.endswith(".tar.gz") and Path(src).is_file():
        from installer.core.errors import EXIT_INTEGRITY_FAIL, InstallerError
        from installer.dist.make_release import verify_archive
        try:
            digest = verify_archive(src, checksum_file=checksum)
        except SystemExit as e:
            raise InstallerError(str(e), EXIT_INTEGRITY_FAIL)
        import tarfile
        with tarfile.open(src, "r:gz") as tar:
            members = tar.getmembers()
            top = (members[0].name.split("/")[0] + "/") if members else ""
            tar.extractall(dest.parent / "_archive_tmp")
        tmp = dest.parent / "_archive_tmp"
        inner = tmp / top.strip("/") if top else tmp
        if dest.exists():
            shutil.rmtree(dest)
        shutil.move(str(inner), str(dest))
        shutil.rmtree(tmp, ignore_errors=True)
        # release manifest travels inside the archive when built properly,
        # else alongside it as genio-<v>.release.json (make_release layout).
        rel = list(dest.glob("*.release.json"))
        if not rel:
            sib = Path(src).parent / (Path(src).name[:-7] + ".release.json"
                                      if src.endswith(".tar.gz") else "")
            if sib.is_file():
                rel = [sib]
        commit = "archive"
        if rel:
            try:
                import json
                commit = json.loads(rel[0].read_text()).get("commit", "archive")
            except (OSError, ValueError):
                pass
        return f"archive:{digest[:12]}", commit
    if (Path(src) / ".git").is_dir() or src.startswith(("http://", "https://", "git@")):
        r = runner.run(["git", "clone", src, str(dest)], timeout=600)
        if not r["ok"]:
            raise InstallerError(f"git clone failed: {r['err'][-400:]}",
                                 EXIT_INSTALL_FAIL, hint="check URL/network")
        return "git"
    if Path(src).is_dir():
        shutil.copytree(src, dest, ignore=shutil.ignore_patterns(
            ".git", "__pycache__", "*.pyc", "node_modules", ".venv", "venv*",
            "*.db", "*.db-journal", "dist", ".pytest_cache"))
        return "copy"
    raise InstallerError(f"source not usable: {src}", EXIT_INSTALL_FAIL)


def _head_commit(repo):
    from installer.core.runner import Runner
    r = Runner().run(["git", "-C", str(repo), "rev-parse", "--short", "HEAD"], timeout=20)
    return r["out"].strip()[:12] if r["ok"] else "unknown"


def _make_venv(runner, venv_path, log):
    r = runner.run(["python3", "-m", "venv", str(venv_path)], timeout=300)
    if not r["ok"]:
        raise InstallerError(f"venv creation failed: {r['err'][-400:]}", EXIT_INSTALL_FAIL)
    pip = venv_path / "bin" / "pip"
    r = runner.run([str(pip), "install", "--upgrade", "pip"], timeout=300)
    if not r["ok"]:
        raise InstallerError("pip upgrade failed", EXIT_INSTALL_FAIL)


def _install_deps(runner, venv_path, repo):
    pip = venv_path / "bin" / "pip"
    req = repo / "requirements.txt"
    if not req.is_file():
        raise InstallerError("requirements.txt missing from source", EXIT_INSTALL_FAIL)
    r = runner.run([str(pip), "install", "-r", str(req)], timeout=1800)
    if not r["ok"]:
        raise InstallerError(f"pip install failed: {r['err'][-500:]}",
                             EXIT_INSTALL_FAIL,
                             hint="see log; missing system libs (libsndfile1?)")
    return True


def _build_frontend(runner, repo, npm_ok):
    client = repo / "genio_client"
    if not (client / "package.json").is_file():
        return {"status": "NOT_APPLICABLE", "detail": "no frontend in source"}
    if not npm_ok:
        return {"status": "NOT_APPLICABLE",
                "detail": "npm absent — frontend skipped honestly, API unaffected"}
    r = runner.run(["npm", "ci", "--no-audit", "--no-fund"], cwd=client, timeout=1200)
    if not r["ok"]:
        return {"status": "FAIL", "detail": f"npm ci failed: {r['err'][-300:]}"}
    r = runner.run(["npm", "run", "build"], cwd=client, timeout=1200)
    if not r["ok"] or not (client / "dist" / "index.html").is_file():
        return {"status": "FAIL", "detail": "frontend build produced no dist/index.html"}
    return {"status": "PASS", "detail": "dist/index.html built"}


def _write_env(env_file, api_key, extra):
    env_file.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by genio installer — edit carefully.",
        "GENIO_ENV=dev",
        "GENIO_SECURITY_MODE=development",
        "GENIO_SANDBOX_MODE=local",
        "GENIO_ALLOW_CLOUD=",
    ]
    if api_key:
        lines.append(f"GENIO_API_KEY={api_key}")
    for k, v in (extra or {}).items():
        lines.append(f"{k}={v}")
    env_file.write_text("\n".join(lines) + "\n")
    try:
        import os
        os.chmod(env_file, 0o600)
    except OSError:
        pass


def install(runner, prefix, source, version, opts):
    """Fresh prefix install. Returns manifest. Raises InstallerError."""
    lay = layout(prefix)
    for d in ("meta", "repo", "config", "data", "cache", "logs", "tmp"):
        lay[d].mkdir(parents=True, exist_ok=True)
    if opts.get("force"):
        import shutil as _sh
        if any(lay["repo"].iterdir()):
            trash = lay["backups"] / f"repo-before-force-{lay['repo'].stat().st_mtime_ns}"
            lay["backups"].mkdir(parents=True, exist_ok=True)
            _sh.move(str(lay["repo"]), str(trash))
        else:
            lay["repo"].rmdir()  # clone/copytree exigent une destination absente
        # pas de mkdir : clone/copytree créent la destination eux-mêmes
    obtained = _copy_source(runner, source, lay["repo"],
                            checksum=opts.get("checksum"))
    if isinstance(obtained, tuple):
        mode, commit = obtained
    else:
        mode = obtained
        commit = _head_commit(lay["repo"]) if mode == "git" else "copy"
    _make_venv(runner, lay["venv"], runner.log_path)
    _install_deps(runner, lay["venv"], lay["repo"])
    fe = _build_frontend(runner, lay["repo"], opts.get("npm_ok", False))
    ports = dict(opts.get("ports") or {})
    lay["ports_file"].write_text(json.dumps(ports, indent=2, sort_keys=True))
    _write_env(lay["env_file"], opts.get("api_key", ""), opts.get("env_extra"))
    man = new_manifest(lay["prefix"], version, commit,
                       "standalone-archive" if mode.startswith("archive")
                       else ("standalone" if mode == "git" else "standalone-copy"))
    man["ports"] = ports
    record_event(man, "install", f"source={mode} frontend={fe['status']}")
    write_manifest(lay["manifest"], man)
    # Post-install verify: python can import the product from the prefix.
    py = lay["venv"] / "bin" / "python"
    r = runner.run([str(py), "-c",
                    "import sys; sys.path.insert(0, '.');"
                    "import config; print(config.get_config().ollama.primary_model)"],
                   cwd=lay["repo"], timeout=120)
    if not r["ok"]:
        raise InstallerError(f"post-install import verify failed: {r['err'][-400:]}",
                             EXIT_VERIFY_FAIL)
    man["health"] = "healthy"
    record_event(man, "verify", "import check passed")
    write_manifest(lay["manifest"], man)
    man["_frontend"] = fe
    return man
