"""
Genio Autonomous Self-Healing & Reflection Engine (Local-First Edition)
Diagnoses runtime failures, consults local coding models (Qwen-Coder / Ollama),
verifies AST syntax, and heals code automatically.
"""

from __future__ import annotations
import os
import re
import logging
import requests
from pathlib import Path
from typing import Optional

logger = logging.getLogger("genio.evolution.healing")

raw_ollama_host = os.getenv("OLLAMA_HOST", "http://127.0.0.1:11434")
OLLAMA_BASE_URL = raw_ollama_host if raw_ollama_host.startswith("http") else f"http://{raw_ollama_host}"

OPENROUTER_BASE_URL = "https://openrouter.ai/api/v1"
OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY", "")


class SelfHealingEngine:
    def __init__(self, workspace_root: Path = Path("/data/ai_tools/genio")):
        self.workspace_root = workspace_root

    def diagnose_and_fix(self, failed_file: Path, error_trace: str, context_notes: str = "") -> bool:
        """Analyzes traceback, asks local/cloud LLM for full repaired code, tests and patches."""
        logger.info(f"🚑 Self-Healing initiated for {failed_file.name}...")

        if not failed_file.exists():
            logger.error(f"Cannot heal missing file: {failed_file}")
            return False

        original_code = failed_file.read_text(encoding="utf-8")

        prompt = f"""You are the Lead Systems & AI Engineer for Genio.
A runtime error occurred. Analyze the code and traceback below, fix all syntax and runtime bugs, and return ONLY the full valid Python code.

--- BROKEN FILE ({failed_file.name}) ---
{original_code}

--- ERROR TRACEBACK ---
{error_trace}

--- CONTEXT ---
{context_notes}

Respond ONLY with valid Python code inside a single ```python ... ``` block. Do not add markdown text outside the code block.
"""
        fixed_code = self._query_repair_model(prompt)
        if not fixed_code:
            logger.error("❌ Failed to obtain fix from local/cloud models.")
            return False

        # Backup original file
        backup_path = failed_file.with_suffix(".bak")
        backup_path.write_text(original_code, encoding="utf-8")

        # Verify Syntax via AST compilation
        try:
            compile(fixed_code, failed_file.name, "exec")
            failed_file.write_text(fixed_code, encoding="utf-8")
            logger.info(f"✅ Applied verified patch to {failed_file.name} (Backup saved to {backup_path.name})")
            return True
        except SyntaxError as se:
            logger.error(f"❌ Patch generated syntax error: {se}. Rolling back.")
            failed_file.write_text(original_code, encoding="utf-8")
            return False

    def _query_repair_model(self, prompt: str) -> Optional[str]:
        """Tries Local Ollama (qwen2.5-coder:14b or qwen2.5:7b) first, falls back to OpenRouter."""
        # 1. Try Local Ollama First
        for local_model in ["qwen2.5-coder:14b", "qwen2.5:7b", "gemma2:9b"]:
            try:
                res = requests.post(
                    f"{OLLAMA_BASE_URL}/api/generate",
                    json={"model": local_model, "prompt": prompt, "stream": False},
                    timeout=90
                )
                if res.status_code == 200:
                    raw_text = res.json().get("response", "")
                    code = self._extract_code(raw_text)
                    if code:
                        logger.info(f"🧠 Patch successfully generated by local model: {local_model}")
                        return code
            except Exception as e:
                logger.warning(f"Local model {local_model} failed: {e}")

        # 2. Cloud Fallback if API Key exists
        if OPENROUTER_API_KEY:
            try:
                headers = {"Authorization": f"Bearer {OPENROUTER_API_KEY}", "Content-Type": "application/json"}
                payload = {
                    "model": "deepseek/deepseek-r1",
                    "messages": [{"role": "user", "content": prompt}],
                    "temperature": 0.1
                }
                res = requests.post(f"{OPENROUTER_BASE_URL}/chat/completions", headers=headers, json=payload, timeout=90)
                if res.status_code == 200:
                    raw_text = res.json()["choices"][0]["message"]["content"]
                    return self._extract_code(raw_text)
            except Exception as e:
                logger.error(f"Cloud fallback failed: {e}")

        return None

    @staticmethod
    def _extract_code(text: str) -> str:
        match = re.search(r"```python\s*(.*?)\s*```", text, re.DOTALL)
        if match:
            return match.group(1).strip()
        match_generic = re.search(r"```\s*(.*?)\s*```", text, re.DOTALL)
        if match_generic:
            return match_generic.group(1).strip()
        return text.strip()
